parca-dev/parca

main.go, pprofui/server.go
Signed-off-by: Goutham Veeramachaneni <gouthamve@gmail.com>
=> Minor fixes: Lint + Remove private repo ref

README.md, web/README.md, web/package.json, web/src/pages/QueryPage.tsx
- dates and labels had browser fonts, now they use Roboto and monospaced respectively
- added to README on how to get started with UI dev
- added proxy that forwards requests to backend when running frontend with `npm start`
=> UI getting started docs and font fixes

README.md
=> Add link to profiling paper

deployments/jsonnet/conprof/conprof.libsonnet, deployments/manifests/statefulset.yaml
=> jsonnet: Fix templating of image

deployments/jsonnet/conprof/conprof.libsonnet, deployments/manifests/statefulset.yaml
=> deployments: Use StatefulSet Parallel PodManagementPolicy

deployments/jsonnet/conprof/conprof.libsonnet, deployments/manifests/statefulset.yaml
=> deployments: Name port

scrape/scrape.go
=> scrape: Validate scraped profiles

deployments/dev.jsonnet, deployments/jsonnet/conprof/conprof.libsonnet, deployments/main.jsonnet, deployments/manifests/configsecret.yaml, deployments/manifests/roleBindings.yaml, deployments/manifests/roles.yaml, deployments/manifests/service.yaml, deployments/manifests/serviceAccount.yaml, deployments/manifests/statefulset.yaml
=> deployments: Improve jsonnet code structure

web/package.json, web/src/App.tsx
=> Support custom path

.drone.yml, api/api.go, manifest.tmpl
Adds drone.io arm64 build
Also fixes `strconv.Atoi(fromString)` on 32 bit systems returns ant int32, casting to `int64(from)` then looses values and doesn't work
Ref https://github.com/conprof/conprof/issues/44
=> Add arm64 build

.drone.yml, manifest.tmpl
Closes https://github.com/conprof/conprof/issues/44
=> Add arm 32 bit builds

pprofui/pprofui.go
Ref https://github.com/conprof/conprof/issues/51
=> Fix nil pointer dereference panic

config/config.go, scrape/target.go
Ref: https://github.com/conprof/conprof/issues/46
=> Remove cmdline profile scraping

deployments/jsonnet/conprof/conprof.libsonnet
Tested this out with the dev.jsonnet before committing :) 
@metalmatze @povilasv
=> jsonnet: Mount configmap if used

pprofui/pprofui.go, web.go
Signed-off-by: Ben Ye <yb532204897@gmail.com>
Fixes #64 
Add an API for downloading, almost the same as the /pprof API.
=> Support downloading profiles

all.go, api/api.go, main.go, sampler.go, scrape/manager.go, web.go
Add an endpoint on the API to support reloading of the configuration.
=> Add reload config endpoint

go.mod, go.sum, main.go, vendor/github.com/felixge/fgprof/LICENSE.txt, vendor/github.com/felixge/fgprof/README.md, vendor/github.com/felixge/fgprof/fgprof.go, vendor/github.com/felixge/fgprof/format.go, vendor/github.com/felixge/fgprof/go.mod, vendor/github.com/felixge/fgprof/go.sum, vendor/github.com/felixge/fgprof/handler.go, vendor/github.com/felixge/fgprof/pprof.go, vendor/modules.txt
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Added fgprof endpoint.

README.md
Signed-off-by: Bartlomiej Plotka <bwplotka@gmail.com>
=> Be more explicit on README quick start.

Makefile, api/api.go, api/api_test.go, pkg/store/appendable.go, pkg/store/client.go, pkg/store/client_test.go, pkg/store/store.go, pkg/store/store_test.go, pkg/store/storepb/custom.go, scrape/scrape.go
Fix Makefile ordering issue causing build not to be run.
Fix license headers for recently added files.
Fix grpc series iterator incorrect EOF handling.
Fix incorrect scrape context cancellation.
=> *: Fix various build issues

Makefile
=> Replace thanos with conprof in Makefile

api/merge.go, api/merge_test.go
=> api: Fix merge panic

README.md
The readme has been pretty bare for a long time, this adds some more details.
RE: https://www.reddit.com/r/golang/comments/l0tzft/pyroscope_continuous_profiling_software_to_help/
=> README.md: Improve readme and add client section

main.go
Less code to maintain and using what upstream provides :)
=> Simply use the oklog/run SignalHandler

all.go, sampler.go
=> Make configfile optional in sample command if targets provided.

api/api.go, api/api_test.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
Fix #77
=> Add error msg for empty query param

README.md
=> README.md: Add docker run instructions

Dockerfile
=> Dockerfile: Reorder and change storage dir and volume setup

deployments/jsonnet/conprof/conprof.libsonnet, deployments/manifests/service.yaml, deployments/manifests/statefulset.yaml
=> jsonnet: Update default port for jsonnet lib

web/src/actions/query.ts
=> web: Fix path prefix causing double slash

web/src/actions/query.ts, web/src/pages/QueryPage.tsx
=> web: Add path prefix when opening pprof UI

README.md
Let's invite people to chat if they have questions.
Invite link taken from Twitter.
=> Add a chat banner to the README

sampler.go
=> Enable /api/v1/targets endpoint on sampler

api/api.go, api/api_test.go
=> api: Seek to profile timestamp instead of requiring equality

api/api.go, api/api_test.go
=> api: Pass query time range of +/- 5 minutes

pkg/store/client.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
The response of the labels API might have an error. This pr adds a check for it.
=> Check label API error

all.go
Adds the remote write api to the `all` command.
=> all: run grpc writable API

api/api.go
Useful for determining the distribution of range queries
=> query range histogram.

api/api.go, api/merge.go, api/merge_test.go
Records the size of merges being performed
=> merge count historgram.

all.go, api.go, api/api.go, api/api_test.go, api/error.go, api/merge.go, api/merge_test.go, api/render.go, api/render_test.go, pkg/store/endless.go, web.go
=> *: Add query timeout flag

symbol/symbol_store.go, symbol/symbol_store_client.go
=> symbol: Better error wrapping

api.go
=> api.go: Instrument symbol gRPC client with tracing

.github/workflows/container.yml, .github/workflows/jsonnet.yml, .github/workflows/proto.yml, .github/workflows/release.yml, Makefile, Tiltfile
=> Improve Github Actions

.github/workflows/release.yml
=> Trigger vercel deploy hook

.github/workflows/go.yml, .github/workflows/release.yml, .goreleaser.yml
=> Several action improvements

pkg/storage/flamegraph_test.go
Add another test for flame graph aggregation. 
Sadly, I was hoping to find a bug but didn't. Sharing anyway.
=> pkg/storage: Add another flame graph aggregation test

pkg/storage/flamegraph.go, pkg/storage/flamegraph_test.go
The `TestGenerateInlinedFunctionFlamegraph` test failed previously with the Cumulative value being 0 of the non-leaf inlined functions, causing icicle graphs to look odd whenever there was inlining happening.
@metalmatze
=> pkg/storage: Fix inlined items in flamegraph

pkg/symbol/addr2line/dwarf.go
=> symbolisation: Lazily built DWARF look up tables

Dockerfile.dev, Dockerfile.go.dev, Tiltfile, deploy/dev.jsonnet, deploy/jsonnetfile.lock.json, deploy/lib/parca/parca.libsonnet, deploy/tilt/parca-agent-clusterRole.yaml, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml, deploy/tilt/parca-agent-role.yaml, deploy/tilt/parca-agent-roleBinding.yaml, deploy/tilt/parca-ui-deployment.yaml, scripts/local-dev.sh
=> deploy: Update dev environment

README.md, pkg/storage/pprof.go, pkg/storage/pprof_test.go
=> pkg/storage: Fix nil pointer for locations that don't have a mapping

pkg/query/query.go, pkg/storage/pprof.go, pkg/storage/pprof_test.go
Making pprof downloads with the new flat profiles work.
=> pkg/storage: Create GenerateFlatPprof to download pprof profiles

.goreleaser.yml, CONTRIBUTING.md, cmd/parca/main.go, pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/server/server.go, ui/packages/app/web/src/components/ui/Navbar.tsx
UI: The build version is listed in the Header
CLI: Added flag `--version` to dump version information
=> Handling of version (ui, --version, removal of date+builtBy)

pkg/storage/flamegraph_flat.go, pkg/storage/flamegraph_flat_test.go
So far I also cannot see any gaps in any profiles showing up anymore.
=> pkg/storage: Properly inline functions in flat flame graphs

ui/packages/shared/functions/src/index.ts
Please take a look if this is a good fix, @yomete.
=> ui: Fix undefined format and return unformatted number as string

.github/workflows/go.yml, .goreleaser.yml
=> goreleaser: Add -X to ldflags

pkg/parca/parca.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
Fixes #509
=> Remove grpc block option tracer

Tiltfile, deploy/Makefile, deploy/dev.jsonnet, deploy/tilt/parca-agent-clusterRole.yaml, deploy/tilt/parca-agent-clusterRoleBinding.yaml, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml, deploy/tilt/parca-agent-role.yaml, deploy/tilt/parca-agent-roleBinding.yaml, deploy/tilt/parca-agent-serviceAccount.yaml, scripts/local-dev.sh
=> Use latest tagged version of agent for local testing

pkg/symbol/addr2line/dwarf.go
=> symbolizer: Fix error message

Makefile
Fixes dec4c9e911e97cf4cec070b19dcbbd44f107001b
Third time hopefully is a charm.
=> Makefile: Add second arg to container push

go.mod, parca.yaml, pkg/config/config.go, pkg/server/server.go, ui/packages/app/web/src/components/ProfileSelector.tsx, ui/yarn.lock
=> Add human-friendly fgprof profile name/description to UI

pkg/debuginfo/validation.go
=> Fix typo in validation.go

ui/packages/app/web/src/components/MetricsGraph.tsx
=> show full time range on metrics graph rather than available data extent

ui/packages/app/web/src/components/ui/DateTimeRangePicker/index.tsx
=> ui/datePicker: Date Picker overflow fix

cmd/parca/main.go, pkg/debuginfo/debuginfod.go, pkg/debuginfo/store.go, pkg/debuginfo/store_test.go, pkg/parca/parca.go, pkg/symbolizer/symbolizer_test.go
Signed-off-by: Sumera Priyadarsini <sylphrenadin@gmail.com>
=> pkg/debuginfo: Add debuginfod client support

deploy/tilt/parca-agent-clusterRole.yaml, deploy/tilt/parca-agent-clusterRoleBinding.yaml, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml, deploy/tilt/parca-agent-role.yaml, deploy/tilt/parca-agent-roleBinding.yaml, deploy/tilt/parca-agent-serviceAccount.yaml
=> Upgrade agent for local test stack

pkg/columnstore/granule.go, pkg/columnstore/part.go, pkg/columnstore/table.go, pkg/columnstore/table_test.go
Remove the index lock, and uses atomic swaps during compaction, this is definitely not endgame, but it's a start.
=> Remove index lock

.golangci.yml, pkg/symbol/addr2line/go.go, pkg/symbol/elfutils/debuginfofile.go, pkg/symbol/elfutils/elfutils.go, pkg/symbol/symbol.go
=> symbolizer: Make sure vendored debug/elf used

ui/README.md
I removed all instances of NextJS and instructions that were specific to NextJS. I also updated to reflect that we now use Create React App.
=> chore: Update Readme file for UI

ui/packages/app/web/src/components/CompareButton.tsx, ui/packages/app/web/src/components/MatchersInput.tsx, ui/packages/app/web/src/components/MergeButton.tsx
=> area/ui: Fix z-index issues with tooltips

ui/packages/shared/profile/src/TopTable.tsx
The label (name) of each top table row now uses the same function as the flame graph:
=> ui/packages/shared/profile: Use similar function from flamegraph to build node label

.github/workflows/publish.yml
=> Revert "area/ui: Remove Bootstrap step in publish.yml file"

.github/workflows/buf-pr.yaml, .github/workflows/buf-push.yaml
This will make sure our proto is all good on PRs. When there are changes on main those will be automatically uploaded to buf's BSR.
=> Add buf GitHub Actions

proto/buf.lock
Mostly for testing the new buf GitHub Actions
=> proto: Update buf dependencies

ui/packages/shared/components/src/MetricsGraph/index.tsx, ui/packages/shared/components/src/ProfileMetricsGraph/index.tsx, ui/packages/shared/functions/src/index.spec.ts, ui/packages/shared/functions/src/index.ts, ui/packages/shared/functions/src/time.ts, ui/packages/shared/profile/src/ProfileSource.tsx
Fixes #613
Signed-off-by: Rohit Dandamudi <rohitdandamudi.1100@gmail.com>
=> feat: convert moment.js to date-fns

ui/packages/shared/functions/src/time.ts
followup to #681
related comment: https://github.com/parca-dev/parca/pull/681#discussion_r818368231
Signed-off-by: Rohit Dandamudi <rohitdandamudi.1100@gmail.com>
=> chore: make Date smallcase

.github/workflows/docs.yml, Makefile, README.md, deploy/tilt/parca-server-deployment.yaml, env.sh
=> *: Local development fixes

CONTRIBUTING.md
=> Update getting started steps

.github/workflows/docs.yml, .github/workflows/golangci-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/release.yml
=> Fix issues with actions

.github/workflows/go.yml, .github/workflows/jsonnet.yml, .github/workflows/proto.yml, .github/workflows/release.yml, Dockerfile
* Upgrade github actions
* Upgrade base images
Fixes issues with: #755
=> Upgrade build pipeline to go 1.17

deploy/tilt/parca-server-deployment.yaml
=> deploy: Update container args for tilt setup

Dockerfile.dev, Dockerfile.go.dev
=> Pin and upgrade base images for dev containers

pkg/debuginfo/client.go, pkg/debuginfo/store.go
=> debuginfo: Prevent redundant debug info uploads

pkg/query/query_test.go
=> pkg: Fix flaky test for query range

pkg/debuginfo/debuginfod.go, pkg/debuginfo/store.go, pkg/symbol/addr2line/dwarf.go, pkg/symbol/addr2line/symtab.go, pkg/symbol/elfutils/debuginfofile.go, pkg/symbol/elfutils/elfutils.go, pkg/symbol/symbol.go
=> symbolizer: Symtab liner

.github/workflows/golangci-lint.yml, .golangci.yml, env.sh, pkg/storage/head.go
=> *: Upgrade golangci-lint

deploy/dev.jsonnet, deploy/jsonnetfile.lock.json, deploy/lib/parca/parca.libsonnet, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml
=> deploy: Upgrade agent manifests

Makefile
=> Makefile: Fix Make UI task

pkg/debuginfo/client.go, pkg/symbol/elfutils/debuginfofile.go, pkg/symbol/symbol.go
=> debuginfo: Fix several minor issues

.github/workflows/jsonnet.yml, deploy/dev.jsonnet, deploy/tilt/parca-agent-clusterRole.yaml, deploy/tilt/parca-agent-clusterRoleBinding.yaml, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml, deploy/tilt/parca-agent-role.yaml, deploy/tilt/parca-agent-roleBinding.yaml, deploy/tilt/parca-agent-serviceAccount.yaml
=> deploy/tilt: Update local dev manifests

pkg/debuginfo/client.go
=> debuginfo/client: Fix error handling

pkg/query/columnquery.go, pkg/query/columnquery_test.go
Builds on top of https://github.com/polarsignals/arcticdb/pull/17
=> Add label names API implementation for arcticdb

pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/query/columnquery_test.go, pkg/query/query_test.go
Depends on https://github.com/polarsignals/arcticdb/pull/18
=> Allow passing flag to configure database in-memory block size

Tiltfile, deploy/dev.jsonnet, deploy/lib/parca/parca.libsonnet, deploy/tilt/parca-agent-clusterRole.yaml, deploy/tilt/parca-agent-clusterRoleBinding.yaml, deploy/tilt/parca-agent-daemonSet.yaml, deploy/tilt/parca-agent-podSecurityPolicy.yaml, deploy/tilt/parca-agent-role.yaml, deploy/tilt/parca-agent-roleBinding.yaml, deploy/tilt/parca-agent-serviceAccount.yaml, deploy/tilt/parca-server-deployment.yaml
=> local env: Update tilt configs

pkg/profilestore/profilecolumnstore.go
=> profilestore: URLEncode labelsets for directories

Tiltfile
=> Tiltfile: Fix syntax

.github/dependabot.yml, ui/packages/shared/components/src/Button/index.tsx, ui/packages/shared/profile/src/ProfileView.tsx
=> Rename additional class prop

ui/packages/shared/components/src/ProfileSelector/index.tsx
Second time's a charm I guess 😅
=> ui: Fix parca agent cpu description matcher

parca.yaml
Follow up to #990 
cc @metalmatze
=> parca.yaml: Add explanation of additional endpoints to example config

ui/packages/shared/profile/src/TopTable.tsx
=> area/ui: Fix bug in top table sorting

pkg/parcacol/parcacol.go, pkg/query/columnquery.go
Instead of calling `parcacol.FlatProfileToBuffer` and getting back the buffer, I need to be able to `parcacol.FlatProfileToRows` and then only later create the buffer.
=> pkg/parcacol: Create FlatProfileToRows to get back rows

MAINTAINERS.md
=> Add maintainers doc

Makefile
=> make: Fix action name

.github/workflows/container.yml
- replace podman login with cosign login for quay.io
see https://github.com/parca-dev/parca-agent/pull/408#issuecomment-1126974923
successfully running https://github.com/cpanato/testing-ci-providers/runs/6443779351?check_suite_focus=true
/assign @kakkoyun
=> replace podman login with cosign login for quay.io

ui/packages/shared/components/src/ProfileExplorer/index.tsx
=> Using default date range when partial query params are found in the URL

Makefile
=> Fix multi-arch builds

go.mod, go.sum, pkg/parcacol/parcacol.go, pkg/parcacol/sample.go, pkg/query/columnquery.go
Fixes #1062 
(also thanks to passing context everywhere shutdown of Parca is now waaaaaay faster 🎉 )
=> go.mod: Upgrade parquet-go and arcticdb

Makefile, pkg/parcacol/ingest.go, pkg/query/query_test.go
This will run every benchmark with just a single iteration to make sure the benchmarks aren't broken.
=> Update Makefile go/test to run benchmarks once

.goreleaser.yml, scripts/make-containers.sh
=> *: Remove support 32-bit arch

deploy/pyrra/parca-grpc-debuginfo-exists-errors.yaml, deploy/pyrra/parca-grpc-debuginfo-exists-latency.yaml, deploy/pyrra/parca-grpc-debuginfo-upload-errors.yaml, deploy/pyrra/parca-grpc-debuginfo-upload-latency.yaml, deploy/pyrra/parca-grpc-profilestore-errors.yaml, deploy/pyrra/parca-grpc-profilestore-latency.yaml, deploy/pyrra/parca-grpc-query-errors.yaml, deploy/pyrra/parca-grpc-query-latency.yaml, deploy/pyrra/parca-grpc-querylabels-errors.yaml, deploy/pyrra/parca-grpc-querylabels-latency.yaml, deploy/pyrra/parca-grpc-queryrange-errors.yaml, deploy/pyrra/parca-grpc-queryrange-latency.yaml
This is actually a demo that's live on https://demo.pyrra.dev/?filter=%7Bteam=%22parca%22%7D
=> deploy/pyrra: Update demo SLOs for Parca

go.mod, go.sum
=> go.*: Upgrade grpc gateway to v2.10.3

Makefile
Add race detector flag, as we are doing in parca-agent https://github.com/parca-dev/parca-agent/pull/497. Once this PR is merged, and the issues in main are fixed, we can add the flag to our CI runs 
Related to: https://github.com/parca-dev/parca/issues/1176
```
[javierhonduco@computer parca]$ make go/bin ENABLE_RACE=yes
go mod tidy
mkdir -p ./bin
go build -race -tags purego -o bin/ ./cmd/parca
[javierhonduco@computer parca]$ make go/test ENABLE_RACE=yes
go test -race -v `go list ./...`
```
cc @Sylfrena
=> build: Add race detector build flag

proto/buf.lock
=> proto: Upgrade proto dependencies

ui/packages/shared/components/src/ProfileExplorer/index.tsx, ui/packages/shared/components/src/ProfileSelector/index.tsx, ui/packages/shared/store/src/slices/profileSlice.ts
=> area/ui: Reset SearchNodes component after dashboard actions

.github/workflows/publish-ui.yml
Trying out an alternative fix, as I was able to reproduce this locally with `act`.
=> ui: Git checkout command fixed

ui/packages/shared/components/README.md
The last fix seemed to have fixed the Lerna publish, validating once with a test commit to components package.
=> ui: Lerna publish action validation

Makefile, Tiltfile, deploy/Makefile, deploy/dev.jsonnet, scripts/install-minikube.sh, scripts/local-dev.sh
xref: https://github.com/parca-dev/parca-agent/pull/507
=> chore: Improve local dev script

deploy/Makefile, go.mod, go.sum, pkg/symbolizer/symbolizer.go
1. Store symbols with partial failures
Test against the tip of the main using the latest stable release of Agent
=> symbolizer: Fix partial symbolization bug

proto/buf.lock
=> chore: Update buf.lock

Dockerfile.dev, ui/Dockerfile.dev
Follow up to #1301
Closes #1305
=> chore(deps): update node container image to v16

ui/packages/shared/functions/src/index.ts
=> area/ui: Make node searching on Parca UI case insensitive

ui/packages/shared/components/src/ProfileSelector/index.tsx
Here's another "please sort this array" PR :joy: 
Previously the dropdown was unsorted:
=> ui/packages/shared: Sort ProfileTypes in Select dropdown

ui/packages/shared/profile/src/ProfileView.tsx
=> ui: Resetting the icicle graph selection when a new profile is selected

.github/workflows/build-test.yml, .github/workflows/codeql-analysis-go.yml, .github/workflows/codeql-analysis-js.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/go-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/proto-push.yaml, .github/workflows/release-dry-run.yml, .github/workflows/ui.yml, Dockerfile
=> Fix cross-platform container builds

Dockerfile, deploy/lib/parca/parca.libsonnet
=> Fix health check binary download

pkg/parcacol/normalizer.go, pkg/query/pprof_test.go
Based on some observations in https://github.com/parca-dev/parca/issues/1448
=> Improve normalization: dedup samples and locations

pkg/metastore/badger.go
This change takes care of ErrTxnTooBig from badger.
ErrTxnTooBig will be reported in case the number of
pending writes/deletes in the transaction exceeds a certain limit.
Fixes #1397 based on the info and discussion in 
1. https://github.com/dgraph-io/badger/blob/7879d23752c1e34564bc5db4e0a1d598b4473df0/docs/content/get-started/index.md#L141
2. https://github.com/dgraph-io/badger/issues/1242
I've built and deployed to our testing cluster and behaviour looks ok.
Based on the logging, it looks like (in our environment at least),
writes are maxing out with a count of 3933.
I can also verify on the logs that there isn't more than a single retry.
Again this is based on our env so may that needs to be tweaked or configurable
but I wasn't convinced we should retry forever
=> badger: Retry large txn as multiple txns

RELEASE.md
Simple PR to document snapcraft token generation.
=> doc: add instructions for snapcraft tokens

.github/workflows/snap.yml
=> ci: Fix snap action trigger

.github/workflows/release.yml, .github/workflows/snap.yml, .goreleaser.yml
The gift that keeps on giving, I'm not sure why these positional arguments aren't working, I'll take that up separately with the Starcraft team over here.
=> ci: fix snapcraft upload

go.mod, go.sum
This pulls in the fix for persistent storage memory spikes.
=> Bump FrostDB

.github/workflows/ui.yml, Makefile, ui/.eslintignore, ui/packages/app/web/src/index.tsx, ui/packages/shared/components/src/FlamegraphTooltip/index.tsx, ui/packages/shared/components/src/MatchersInput/index.tsx, ui/packages/shared/components/src/MetricsGraph/index.tsx, ui/packages/shared/components/src/MetricsSeries/index.tsx, ui/packages/shared/components/src/ProfileExplorer/index.tsx, ui/packages/shared/components/src/ProfileMetricsGraph/index.tsx, ui/packages/shared/functions/src/index.ts, ui/packages/shared/profile/src/IcicleGraph.tsx, ui/packages/shared/profile/src/ProfileView.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx, ui/packages/shared/profile/src/TopTable.tsx, ui/packages/shared/profile/src/components/DiffLegend.tsx, ui/packages/shared/profile/src/components/ProfileShareButton/index.tsx, ui/packages/shared/profile/src/useDelayedLoader.ts, ui/packages/shared/profile/src/useQuery.tsx
This address all problems reported by ESLint and makes it a required CI check.
Fixes are rather lazy/minimal in order to get it to pass, and I might have messed up a few conditions, I will need help to review and test the changes.
Please feel free to edit the branch if you catch any issues.
=> fix(ui): address all problems reported by ESLint

ui/packages/shared/components/src/MatchersInput/index.tsx, ui/packages/shared/components/src/ProfileMetricsGraph/index.tsx
This fixes the flickering that happens on the Parca UI and also contains another fix for a bug that happens when you try to use the query browser.
=> ui: Fix flickering on Parca UI

pkg/parca/parca.go
Fix: https://github.com/parca-dev/parca/issues/1572
=> bug: exit when store-address is set and the mode is not scraper-only

pkg/scrape/manager.go
Signed-off-by: heylongdacoder <heylongdacoder@gmail.com>
=> pkg/scrape: fix manager reload potential deadlock

pkg/symbol/addr2line/doc.go, pkg/symbol/addr2line/dwarf.go, pkg/symbol/addr2line/go.go, pkg/symbol/addr2line/symtab.go, pkg/symbol/demangle/demangle.go, pkg/symbol/elfutils/debuginfofile.go, pkg/symbol/symbol.go
Hi! I've added some docs for the symbol package. Not sure I got it right though.
=> pkg/symbol: Add docs

.github/workflows/proto-pr.yaml, Makefile, gen/proto/swagger/parca/debuginfo/v1alpha1/debuginfo.swagger.json, gen/proto/swagger/share/share.swagger.json, proto/buf.lock
=> Run `buf mod update`

pkg/parcacol/ingest.go
Fix the log in ingest validatePprofProfile()
=> fix ingest validatePprofProfile log

go.mod, go.sum
This updates FrostDB to use the concurrency.
=> Update FrostDB and use Go 1.19

go.mod, go.sum, pkg/parca/parca_test.go, pkg/query/columnquery_test.go, pkg/query/query_test.go
=> build(deps): update github.com/polarsignals/frostdb digest to aa76fcf

pkg/config/config.go, pkg/config/config_test.go
=> fix(config): ensure path_prefix comes with default pprof_config

ui/packages/shared/profile/src/ProfileView/FilterByFunctionButton.tsx
Fixed the bug where the component state is going out of sync with Redux store.
=> ui: FilterByFunction minor bug fix

ui/packages/app/web/src/components/ui/Navbar.tsx, ui/packages/app/web/src/components/ui/UserPreferences.tsx, ui/packages/app/web/tailwind.config.js, ui/packages/shared/components/src/Button/index.tsx, ui/packages/shared/components/src/index.tsx, ui/packages/shared/functions/package.json, ui/packages/shared/functions/src/useUIFeatureFlag/index.ts, ui/packages/shared/profile/src/ProfileView/FilterByFunctionButton.tsx, ui/yarn.lock
=> ui: UI user preferences

.github/workflows/pre-commit.yml
This is a new action which will apply pre-commit automatic fixes to the branch (e.g. formatting)
https://pre-commit.ci/lite.html
=> ci(pre-commit): apply automatic fixes

ui/packages/app/web/src/App.tsx, ui/packages/shared/profile/package.json, ui/packages/shared/profile/src/useGrpcQuery/index.ts, ui/packages/shared/profile/src/useQuery.tsx, ui/yarn.lock
=> ui: Query data caching on the Frontend

ui/packages/shared/profile/src/ProfileSource.tsx
cc @yomete @manojVivek @monicawoj
=> ui: URL encode label-values in single profile URL params

README.md, pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/parcacol/querier.go, pkg/profilestore/profilecolumnstore.go, pkg/profilestore/profilestore_test.go, pkg/query/columnquery_test.go, pkg/query/query_test.go, pkg/symbolizer/symbolizer_test.go
- profilestore: remove debug value log
- parcacol: add logging
=> parca: minor fixes

.github/workflows/container.yml, .github/workflows/release.yml, Makefile
* Use `$(CMD_GIT)` consistently
* Do not hide errors from `git describe` (hopefully this will help identifying the error next time)
* Simplify setting `GITHUB_BRANCH_NAME` and generalize `refs/` prefix trimming
* Filter out UI tags from `git describe`
* Ensure `$(BRANCH)` does not have any `/` characters
* Replace `which` by Bash's built-in `command -v`
=> ci: minor fixes to Makefile

.github/workflows/release.yml
Related to parca-dev/parca-agent#1253 / parca-dev/parca-agent#1256
=> ci(release): fix "detected dubious ownership in repository"

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/useColoredGraph.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/useNodeColor.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/store/src/slices/colorsSlice.ts
Resolves: https://github.com/parca-dev/parca/pull/2381#issuecomment-1410343550
=> ui: flamegraph color stacks bug and alignment fixes

pkg/symbol/addr2line/symtab.go, pkg/symbol/addr2line/symtab_test.go, pkg/symbol/symbolSearcher/symbolSercher.go, pkg/symbol/symbolsearcher/symbol_searcher.go
Fixes https://github.com/parca-dev/parca/issues/2056
Context:
https://maskray.me/blog/2021-09-19-all-about-procedure-linkage-table
https://upload.wikimedia.org/wikiversity/en/d/db/Ex2.A.DynamicLinkEx.20190121.pdf
=> pkg/symbol: Add priority for symtab search and support plt symbol

pkg/symbolizer/symbolizer.go
refactor code, move close and remove file into defer function.
in go, it is ok to read file if there have open file descriptor after remove file.
=> pkg/symbolizer: refactor code

ui/packages/app/grafana-datasource-plugin/src/datasource.ts, ui/packages/app/grafana-panel-plugin/src/ParcaPanel.tsx, ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx, ui/packages/shared/profile/src/ProfileSource.tsx
Closes #2617 
Right now it's missing the label propagation from the input field though. Any ideas how to propagate those?
=> ui: Add labels to query when clicking on metrics sample

pkg/symbolizer/symbolizer.go
continuation of the work in https://github.com/parca-dev/parca/pull/2491
=> pkg/symbolizer: Use symbols liner either HasSymtab or HasDynsym

ui/packages/shared/components/src/KeyDownContext/index.tsx, ui/packages/shared/components/src/NoDataPrompt/index.tsx, ui/packages/shared/components/src/hooks/useURLState.tsx, ui/packages/shared/functions/src/index.ts, ui/packages/shared/profile/src/TopTable/index.tsx, ui/packages/shared/profile/src/components/ProfileShareButton/ResultBox.tsx
This will unblock updates to other projects using these @parca components
=> Add a conditional check for `window` usage

ui/packages/shared/components/src/Button/index.tsx, ui/packages/shared/components/src/Input/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/components/ProfileShareButton/index.tsx
These slight adjustments will fix the rogue buttons in the visualization toolbar.
Tested this by releasing an alpha version and using it in the cloud project.
=> ui: Fix buttons CSS in visualization toolbar

Dockerfile.dev, Dockerfile.go.dev, ui/packages/shared/profile/src/ProfileExplorer/index.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
This PR addresses two issues that we were encountering:
1) Selected point in metrics graph & Flamegraph were not appearing despite this information being in the URL (shareability fix)
2) Flamegraph was not being updated for delta type profiles on time selection in the metrics graph
=> Shareability fixes

.goreleaser.yml
Fixes: https://github.com/parca-dev/parca/issues/2673
=> Fix archive filename template

deploy/lib/parca/parca.libsonnet
reflects the changes introduced in https://github.com/parca-dev/parca/pull/2193
=> deploy: Update config after flag changes

ui/packages/shared/components/src/Select/index.tsx
This fixes the profile type selector without negative side effects on the other dropdowns (Add Panel, panel type selector). 
Resolves #2809
=> fix profile selector

pkg/query/flamegraph.go, pkg/query/flamegraph_flat_test.go, pkg/query/flamegraph_table.go, pkg/query/flamegraph_table_test.go, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/utils.ts
There are some other bugs that still need to be fixed tomorrow, but at least it doesn't crash the UI anymore.
=> Fix string trimming table bugs

ui/packages/app/grafana-panel-plugin/src/ParcaPanel.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx
Not exactly sure about the types with Number and BigInt. Where to convert.
=> ui/ProfileView: Pass total and filtered into ProfileView

pkg/parcacol/sample.go
=> append final record for when rowsPerRecord is greater than number of

.github/workflows/chromatic.yml
Forks do not have the token to publish.
=> ci(chromatic): skip forks entirely

.github/workflows/chromatic.yml
=> ci(chromatic): fix fork check

Dockerfile
This will enrich the registry UI and tools like Renovate (changelog) with metadata
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#labelling-container-images
Related to parca-dev/parca-agent#1633
=> build(container): add metadata labels

.github/workflows/container.yml, .github/workflows/release-dry-run.yml, .github/workflows/release.yml, .github/workflows/snap.yml, Makefile
=> Update goreleaser to use `--clean`

ui/packages/shared/profile/src/GraphTooltip/index.tsx
=> ui: Fixes the flame graph tooltip overflow when multiple visualizations are enabled

ui/packages/shared/profile/src/ProfileTypeSelector/index.tsx
Improve fgprof profiles in profile types dropdown
Fixes: #3199
Corrected the key value so that the appropriate dropdown value is shown.
=> bug fix: corrected the key for profile-selector

ui/packages/shared/components/src/KeyDownContext/index.tsx
After recent changes, directly following a screenshot, the user needed to hit 'command' once in order for the tooltip selection to work properly. This PR resolves that issue.
=> fix tooltip freeze bug

ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx
=> ui: Add loading indicator when downloading pprof

ui/packages/app/web/src/App.tsx
Making this change based on the suggestions from Meticulous.
=> ui: Enabled /PATH_PREFIX_VAR to all environments to fix a meticulous difference

pkg/query/flamegraph_arrow.go
Same as https://github.com/parca-dev/parca/pull/3552
=> pkg/query: Replace remaining slices.Clone

renovate.json, ui/package.json, ui/yarn.lock
=> ui: UI Build failure fix

pkg/query/flamegraph_arrow.go
We want to break down the gigantic function into smaller pieces to improve readability, maintainability, and overall observability for profiling and tracing.
There's probably more to refactor in the `generateFlamegraphArrowRecord` when iterating over `locations` and `stacktraces` but I want to take this one step at a time.
=> Refactor the flamegraphBuilder

ui/packages/app/web/src/pages/index.tsx, ui/packages/shared/components/src/ParcaContext/index.tsx, ui/packages/shared/profile/package.json, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileView/ProfileViewContext.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx, ui/packages/shared/profile/src/SourceView/Highlighter.tsx, ui/packages/shared/profile/src/SourceView/LineNo.tsx, ui/packages/shared/profile/src/SourceView/index.tsx, ui/packages/shared/profile/src/useQuery.tsx, ui/yarn.lock
=> ui: Sources Panel UI improvements

ui/packages/shared/profile/src/ProfileSelector/index.tsx
Something about extracting the header into being a function messed with re-rendering it.
=> ui: Fix unexpectedly unfocusing matchers input

ui/packages/shared/profile/src/ProfileView/VisualizationPanel.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx
Fixes error seen in pprof.me and introduces one additional styling modification
=> fix profile view header bug and button spacing

pkg/query/sources.go, pkg/query/sources_test.go
=> fix memory leak

ui/packages/shared/profile/src/ProfileViewWithData.tsx
=> fix(ui): remove unused tableFromIPC import

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
It's not used anywhere in the frontend.
=> pkg/query/flamegraph_arrow: Remove locationFolded column

pkg/query/flamegraph_arrow_test.go
=> pkg/query: Fix test

pkg/query/flamegraph_arrow.go
Added the very first `Bytes` line and the `BYTES PERCENT` column in the table. 
```
Bytes: 1066955
Cols: 15
Rows: 9530
+----------------------+--------------+--------------+---------------+------------+----------------------------------------------------------+
|         NAME         |    BYTES     | BITMAP BYTES | BYTES PERCENT |   COUNT    |                           TYPE                           |
+----------------------+--------------+--------------+---------------+------------+----------------------------------------------------------+
| labels_only          |         1192 |         2048 |         0.30% |       9530 | bool                                                     |
| mapping_start        |        76240 |         2048 |         7.34% |       9530 | uint64 …
```
=> pkg/query: Create bytes percent column to recordStats

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleGraphNodes.tsx
=> Choose optimal integer types based to minimize size

ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx
- ui/profile/IcicleGraph: Fix GroupBy dropdown background color
- ui/profile/IcicleGraph: Always group by function name
=> ui/profile/icicle: Always group by function name

pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/pprof.go, pkg/query/pprof_test.go
This completes all currently used APIs being served by arrow internally.
=> pkg/query: Build pprof directly from arrow records

ui/packages/app/web/src/pages/index.tsx, ui/packages/shared/components/src/ParcaContext/index.tsx, ui/packages/shared/profile/src/SourceView/Highlighter.tsx, ui/packages/shared/profile/src/useQuery.tsx
=> ui: Source View fixes

pkg/parcacol/arrow.go
The only reason this conversion is done to pass a byte slice to append, these slices are never modified, which would be unsafe, so this optimization is safe to do and saves ~10% of CPU cycles in the Query path.
=> pkg/parcacol: Don't allocate during string to byte conversion

pkg/query/columnquery.go
1) Only lowercase and convert filter string to bytes once.
2) Run filter on dictionary only and then match indices. 
3) Run filter on all lines of a sample's locations at once to exit loop
earlier.
Filtering itself is 52% faster.
```
name                  old time/op  new time/op  delta
FilterProfileData-10  0.05ns ± 1%  0.02ns ± 4%  -52.41%  (p=0.000 n=10+10)
```
And requests in total that filter about 17%.
```
name                            old time/op  new time/op  delta
ColumnQueryAPIQueryFiltered-10   136ms ± 3%   112ms ± 4%  -17.62%  (p=0.008 n=5+5)
```
=> pkg/query: Improve filter performance

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/DockedGraphTooltip/index.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/useGraphTooltipMetaInfo/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx
=> *: Show whether function was inlined in hover bubble.

pkg/parcacol/normalizer.go, pkg/query/table_test.go, pkg/symbolizer/symbolizer_test.go
Fixes https://github.com/parca-dev/parca-agent/issues/2096
=> pkg/parcacol: Ensure base address normalizaton only happens once

ui/packages/shared/profile/src/MetricsGraph/MetricsContextMenu/index.tsx, ui/packages/shared/profile/src/MetricsGraph/MetricsInfoPanel/index.tsx, ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ContextMenu.tsx
Implements an info panel to inform users of what different types of clicks can do in the Metrics Graph
Design: https://www.figma.com/file/sMMnQwWpPovvn5JM3vhwL7/Parca?type=design&node-id=492-245232&mode=design&t=sNbDSDXIRgg4Om5G-4
=> Metrics Graph - click info panel

ui/packages/shared/components/src/Button/index.tsx, ui/packages/shared/profile/src/MetricsGraph/MetricsContextMenu/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ContextMenu.tsx
=> ui: Context menu to use darkMode state from Parca Context to support downstream integrations

ui/packages/shared/profile/src/MetricsGraph/index.tsx
=> Metrics graph axis labels

README.md
Thank you [Meticulous](https://meticulous.ai/?utm_source=parca&utm_campaign=oss) for providing your service to Parca for free! :100:
=> Add Meticulous to our README

ui/packages/app/web/package.json, ui/packages/app/web/src/index.tsx, ui/yarn.lock
This is requested from Meticulous team as an improvement.
=> ui: Meticulous fixes

ui/packages/shared/profile/src/MatchersInput/index.tsx
=> ui: Minor auto suggestion improvements to eliminate pauses in query builder

.github/workflows/container.yml, .github/workflows/release.yml
CI is failing with ```Error response from daemon: manifest for quay.io/containers/podman@sha256:68314bb5d90419aece81d33e1b5e18ac7dba9cf6d98d53aa6c10006442e3ece3 not found: manifest unknown: manifest unknown```
=> Fixes the podman image in CI

README.md
=> Update Meticulous logo in README.md

ui/packages/shared/utilities/src/index.ts
=> Bug fix for double encoding the expression

ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileMetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
Fixes https://github.com/parca-dev/parca/issues/4314
=> Use sample duration for merge query instead of step

ui/packages/shared/profile/src/SourceView/index.tsx
=> ui: Source view context menu polish

.github/workflows/jsonnet.yml, README.md, ui/packages/app/grafana-datasource-plugin/README.md, ui/packages/app/grafana-datasource-plugin/src/plugin.json
Add missing commas, correction of spelling errors
=> Add missing commas, correction of spelling errors

README.md, pkg/parca/parca.go
Added a flag to enable on-disk compactions to index files.
=> Add new flag to use an on-disk index

.github/workflows/release-dry-run.yml, .github/workflows/release.yml, scripts/free_disk_space.sh
Merge this back from `release-0.21` into `main` so we don't fail there always.
=> Free disk space before releasing

ui/packages/app/grafana-panel-plugin/src/ParcaPanel.tsx, ui/packages/shared/profile/src/Callgraph/index.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/DockedGraphTooltip/index.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/useGraphTooltip/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ContextMenu.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleGraphNodes.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileView/ProfileViewContext.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx, ui/packages/shared/profile/src/SourceView/Highlighter.tsx, ui/packages/shared/profile/src/Table/index.tsx
Rather than only passing the sampleUnit into components, we want to pass the profileTypes into components. It also includes whether a profile is a delta profile.
=> ui/packages/shared/profile: Pass profileType into all components

pkg/parcacol/querier.go
Since it's possible to have delta profiles that aren't cpu/nanoseconds we still need to query them correctly.
Additionally, setting the resultType is fixed again too.
=> pkg/parcacol: Correctly handle delta non cpu/ns profiles

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ColorStackLegend.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/Table/index.tsx
This ensures that the legend will always be persistent (i.e. the metadata call isn't called again) when clicking through binaries.
=> ui: Refactor the `ColorStackLegend` component to be outside the icicle graph component

ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/DockedGraphTooltip/index.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/useGraphTooltip/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ContextMenu.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx, ui/packages/shared/profile/src/Table/index.tsx
=> ui: Call view Bug fixes

ui/packages/app/web/src/components/ui/Navbar.tsx, ui/packages/shared/profile/src/ProfileExplorer/ProfileExplorerCompare.tsx, ui/packages/shared/profile/src/ProfileExplorer/ProfileExplorerSingle.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx, ui/packages/shared/profile/src/ProfileSelector/useAutoQuerySelector.ts, ui/packages/shared/profile/src/index.tsx, ui/packages/shared/profile/src/utils.ts
This ensures that the Compare button successfully opens the comparison mode for profiles by automatically comparing CPU profiles in the last 15 mins.
=> ui: Auto compare profiles

pkg/query/columnquery.go
This prevents an underlying memory leak from occurring
=> ComputeDiff: Release created arrays

ui/packages/shared/components/src/DateTimePicker/index.tsx, ui/packages/shared/components/src/DateTimeRangePicker/AbsoluteDatePicker/index.tsx, ui/packages/shared/profile/src/ProfileMetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
=> ui: Date picker fixes

pkg/parcacol/querier.go, pkg/profile/profile.go, pkg/profile/reader.go, pkg/profile/writer.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
This basically reverts #4525 and follows up after #4892
=> pkg: Remove perSecond columns

ui/packages/shared/profile/src/SimpleMatchers/Select.tsx
This potentially fixes a CI build failure upstream.
=> area/ui: Add `null` check on ref

ui/packages/shared/profile/src/SimpleMatchers/Select.tsx, ui/packages/shared/profile/src/SimpleMatchers/index.tsx
=> area/ui: Enable the RegEx matchers for simple querying mode

ui/packages/shared/profile/src/ProfileSelector/index.tsx, ui/packages/shared/profile/src/SimpleMatchers/index.tsx, ui/packages/shared/profile/src/components/VisualisationToolbar/MultiLevelDropdown.tsx
This updates IDs for recently created components in the Parca UI. This will be used upstream for product tours.
=> area/ui: Update Ids for components

pkg/profile/encode.go
=> pkg/profile: Guard against null file

ui/packages/shared/profile/src/ProfileView/components/ActionButtons/GroupByDropdown.tsx
=> area/ui: auto close the group by dropdown when there's an outside click

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/ColorStackLegend.tsx, ui/packages/shared/profile/src/ProfileView/components/ColorStackLegend.tsx, ui/packages/shared/profile/src/ProfileView/hooks/useProfileMetadata.ts, ui/packages/shared/profile/src/SimpleMatchers/Select.tsx, ui/packages/shared/profile/src/Table/index.tsx, ui/packages/shared/profile/src/Table/utils/functions.ts
- When using the simple querying mode and in the regex mode, the cursor will now always be positioned at the end of the text.
- The border radius of the binary in the Legend and Table components is now uniform.
- The binary column in the Table component now shows the binary name (via a tooltip) when hovered on.
=> Parca UI improvements

ui/packages/shared/components/src/UserPreferences/index.tsx, ui/packages/shared/hooks/src/useUserPreference/index.ts, ui/packages/shared/profile/src/ProfileView/components/ViewSelector/index.tsx
=> ui: Option to enable Iciclechart visualization for CPU profiles

ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
Screencast:
https://github.com/user-attachments/assets/68ce2666-84af-4f01-9bff-f22803a4eea1
=> ui: Indicating sum by loading state in the UI

ui/packages/shared/components/src/hooks/URLState/index.tsx
=> ui: Minor URL State improvements

ui/packages/shared/components/src/hooks/URLState/index.tsx
=> ui: URL State type changes

ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx, ui/packages/shared/utilities/src/index.ts
Updated the utility functions and Y-axis unit mapping to handle Celsius and Hertz.
=> Add support for Celsius and Hertz units in metrics handling

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Previously no matter at what time, if the parent had a child frame at some point in time we incorrectly merged with that frame.
=> pkg/query: Flamechart only merge if very last sample had frame

ui/packages/shared/profile/src/MetricsGraph/MetricsContextMenu/index.tsx
=> ui: Fix the labels submenu to show appropriate message and scrollbars only when necessary

MAINTAINERS.md
After much consideration, I’ve decided to step down as a maintainer.
It’s been an honor to be part of this community — I’ve learned a lot and truly appreciate the opportunity.
- Move @kakkoyun to "Emeritus Maintainers"
=> Stepping down as a maintainer

pkg/server/server.go
Call [http2.ConfigureServer](https://pkg.go.dev/golang.org/x/net/http2#ConfigureServer) to register graceful shutdown and avoid forceful termination of connections on shutdown
https://cs.opensource.google/go/x/net/+/refs/tags/v0.43.0:http2/server.go;l=268
=> fix(server): register HTTP/2 server graceful shutdown

ui/packages/shared/components/src/DateTimeRangePicker/DateTimeRangePickerText/index.tsx, ui/packages/shared/components/src/DateTimeRangePicker/index.tsx, ui/packages/shared/profile/src/MatchersInput/index.tsx, ui/packages/shared/profile/src/MetricsGraph/MetricsContextMenu/index.tsx, ui/packages/shared/profile/src/MetricsGraph/MetricsTooltip/index.tsx, ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileExplorer/ProfileExplorerCompare.tsx, ui/packages/shared/profile/src/ProfileFlameGraph/index.tsx, ui/packages/shared/profile/src/ProfileMetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx, ui/packages/shared/profile/src/ProfileTypeSelector/index.tsx, ui/packages/shared/profile/src/ProfileView/components/DiffLegend.tsx, ui/packages/shared/profile/src/ProfileView/components/GroupByLabelsDropdown/index.tsx, ui/packages/shared/profile/src/ProfileView/components/ProfileFilters/index.tsx, ui/packages/shared/profile/src/ProfileView/components/Toolbars/index.tsx, ui/packages/shared/profile/src/SimpleMatchers/index.tsx, ui/packages/shared/profile/src/ViewMatchers/index.tsx, ui/packages/shared/test-utils/src/test-ids.ts
This PR removes the hardcoded test ids from the components.
=> ui: Test id refactoring to remove the hardcoded strings

pkg/normalizer/normalizer.go, pkg/scrape/manager.go, pkg/scrape/scrape.go
=> Add `parca_target_samples_total` metric to track total scraped samples
