parca-dev/parca

README.md
git cloning and then running go install works, so let's use that in the QuickStart guide.
/cc @brancz @cstyan @LiliC 
Closes #10
=> Improve QuickStart to use git clone and go install

main.go, sampler.go, scrape/scrape.go
This changes block creation to start at 10 minutes, then compacted to 1 hour blocks and then the usual 2h, 8h, etc. compaction steps.
I've tested this for several days and it works just fine.
@metalmatze
=> Short blocks

config/config.go
Fixes #33 
Because everything in the config structs is a pointer we need to take care that they don't all point to the same global variable.  It seems neatest to do this by introducing two functions whose return value
escapes.
If they all point to the same place then whatever value is read last by `UnmarshalYAML()` will apply to all of them.
=> Give each scrape config its own memory

scrape/scrape.go
The [comment on tsdb.Appender](https://github.com/conprof/conprof/blob/ccbcf2069b2abbae7ab2dcb7304c88a2389c36df/vendor/github.com/conprof/tsdb/db.go#L85) says "It must be completed with a call to Commit or Rollback and must not be reused afterwards".
Fixes #34, I believe - the reused Appender would keep resetting the `minTime` on head to its oldest value which prevents anything from being removed.
=> Don't re-use appender after calling Commit()

deployments/jsonnet/conprof/conprof.libsonnet
The config only potentially holds secrets, but not in practice (at least in Kubernetes). Some organizations limit actions on secrets and thus prefer configmaps for actual configs.
@metalmatze
=> jsonnet: Allow using configmap instead of secret

api/api.go, config/config.go, main.go, scrape/scrape.go, scrape/target.go, web/src/model/model.ts, web/src/pages/QueryPage.tsx, web/web.go
REF https://github.com/conprof/conprof/issues/46
as  we are using special `__name__` label for profile types everything works, with current tsdb setup
Includes:
- Added UI rendering.
- Added Trace parsing, now Traces will be scrapped correctly instead of erroring out.
- Added Seconds argument to Trace/ Profile scrape jobs, which are set to their defaults in Go:
>Profile responds with the pprof-formatted cpu profile. Profiling lasts for duration specified in seconds GET parameter, or for 30 seconds if not specified. The package initialization registers it as /debug/pprof/profile. 
>Trace responds with the execution trace in binary form. Tracing lasts for duration specified in seconds GET parameter, or for 1 second if not specified. The package initialization registers it as …
=> Add Profile Type

Dockerfile
Updates alpine to 3.11 and thus graphviz: 2.40.1-r1 -> 2.42.3-r0
Sets WORKDIR early so the mkdir call is not required.
=> Dockerfile: Set workdir early/Update to alpine 3.11

sampler.go, scrape/manager.go
Before the reloader only reloaded a subpart of the service.
Now it reapply the config and trigger a reload of the discovery which reloads the scrapers
#70
=> Fix the reloader api

config/config_test.go
From `loaclhost` to `localhost` :smile: 
Signed-off-by: Daniel González Lopes <danielgonzalezlopes@gmail.com>
=> Fix typo on test target

README.md
Running `conprof all --help` displays `--http-address` flag instead of  `--web.listen-address`.
Signed-off-by: Daniel González Lopes <danielgonzalezlopes@gmail.com>
=> Fix quickstart HTTP flag

sampler.go
There was a diplicate discoveryManager that was being created and being unused.
=> remove duplicate discoveryManager

scrape/manager.go
This prevents the scrape reloads from being skipped by the default
case in the select statement, and only takes that branch in the event
a reload is already pending in channel.
=> scrape manager buffer reload channel

api/api.go, api/api_test.go, web/src/pages/QueryPage.tsx
This was a massive hack to get Conprof off the ground in the beginning
but it makes the API much cleaner to skip this as it's really leaking
logic from the broken way the pprof UI works.
cc @yeya24 as this likely affects your Grafana plugin
=> api: Remove encoded labels from API response

pkg/store/client.go, test/e2e/e2econprof/services.go, test/e2e/storage_test.go
This gives us a better representation of what a user might experience as
opposed to just checking against the internal gRPC API result as this is
exactly what the frontend would show.
=> Extend restart e2e

api/api.go, pkg/store/store.go, scrape/scrape.go, test/e2e/all_test.go, test/e2e/e2econprof/services.go, test/e2e/storage_test.go
Labels must be consistently sorted at insertion time, so that hashing of
a label-set is consistent.
=> Fix non-continuous series after restart

config/config.go, scrape/target.go, test/e2e/e2econprof/services.go
Until we have a way to display trace profiles we should disable them
from being collected, as the errors cause more confusion than good.
=> *: Remove trace profile collection

api/api.go, api/api_test.go
Turns out this never made sense semantically.
=> api: Remove filtering exact matcher label names

api/flamegraph.go, api/flamegraph_test.go
Previously because of map order being random results may have been in random order, which can be confusing.
=> api: Deterministic results

all.go, api.go, api/api.go, api/api_test.go, config/config.go, main.go, sampler.go, scrape/manager.go, store.go, web.go
A lot of the imports are automatically grouped and sorted by my editor, but should follow the guidelines of this project from what I can see.
I needed to do a bunch of plumbing to pass the configReloaders through all components properly and I think that the individual components registering the `ApplyConfig` is probably cleanest in terms of dependencies.
=> Create configReloaders to synchronize config for api /api/v1/status/config

main.go
Otherwise the web handler won't have the proper config to serve until a reload is triggered once.
Currently the config handler actually panics. I didn't realize during dev earlier, as I constantly reloaded :grin:
=> Synchronize all reloaders for the first time

all.go, api.go, api/api.go, api/api_test.go, internal/pprof/report/source_test.go, pkg/store/store_test.go, web.go
This should make things more maintainable in the future. 
While refactoring this I discovered that I only added the `api/v1/status/config` to _web_ but not _api_...
=> Create http router for api for reusability

all.go, api.go, api/api.go, api/api_test.go, go.sum, pkg/store/store_test.go, sampler.go, scrape/scrape.go, scrape/target.go, test/e2e/all_test.go, web.go
I've also restructured how the Sampler and Web component are created to allow for better extensibility in the future. This was needed to be able to pass the `scrape.Manager` to the Web -> API.
Some rough edges that I'm happy to follow up in the future.
=> Add /api/v1/targets API

api/render_test.go, api/svg_test.go
Signed-off-by: Matt Layher <mdlayher@gmail.com>
I ran into this when attempting to package conprof on NixOS. The SVG renderer tests should use dot if it's available, but gracefully degrade if not.
=> api: add helper to skip tests if graphviz is missing

all.go, store.go
Previously we were passing nanoseconds instead of the expected
milliseconds.
Fixes #160
=> *: Fix retention parameter

api.go, api/api.go, api/api_test.go, pkg/store/store_test.go, sampler.go, web.go
/cc @lilic 
Sadly the prefix isn't able to just be done on the outside, as the current routers don't support routing. For that I'd suggest using go-chi/chi in the future.
Still a lot cleaner already.
=> Refactor api.New() to take options for optional config

.github/workflows/main.yml, api/flamegraph_test.go, api/merge.go, api/merge_test.go, api/render.go, api/render_test.go, api/svg_test.go, pkg/store/endless.go
Hi @brancz, @metalmatze,
This add the default `Makefile.common` target `check_license` to the CI, and fix its existing issues.
=> Fix Makefile.common check_license target

pkg/storage/metastore/sql.go, pkg/storage/metastore/sql_bench_test.go
This often shows up in large queries of previously unqueried data.
```
name                               old time/op    new time/op    delta
BuildLocationsByIDsQuery/1-8          378ns ± 0%      89ns ± 0%   ~     (p=1.000 n=1+1)
BuildLocationsByIDsQuery/10-8        1.42µs ± 0%    0.17µs ± 0%   ~     (p=1.000 n=1+1)
BuildLocationsByIDsQuery/100-8       20.8µs ± 0%     0.9µs ± 0%   ~     (p=1.000 n=1+1)
BuildLocationsByIDsQuery/1000-8      1.46ms ± 0%    0.02ms ± 0%   ~     (p=1.000 n=1+1)
BuildLocationsByIDsQuery/10000-8      129ms ± 0%       0ms ± 0%   ~     (p=1.000 n=1+1)
BuildLocationsByIDsQuery/100000-8     12.5s ± 0%      0.0s ± 0%   ~     (p=1.000 n=1+1)
name                               old alloc/op   new alloc/op   delta
BuildLocationsByIDsQuery/1-8           144B ± 0%      128B …
```
=> pkg/storage/metastore: Optimize SQL query building of locations by ids

pkg/storage/metastore/metastore.go
I think this should fix https://github.com/parca-dev/parca/issues/261
In dynamic languages (such as javascript, ruby, python) we don't actually have a memory address that we can resolve to a symbol in a stable way, so the address is not a useful identifier for the location, only the true file, function, and line number is.
=> pkg/storage/metastore: Fix location key

.github/dependabot.yml
@kakkoyun and I felt like npm updates are quite a lot, so we propose to only run them weekly.
=> Update dependabot to only send weekly npm PRs

pkg/storage/flamegraph_flat.go, pkg/storage/flamegraph_flat_test.go
To get rid of the ProfileTree going forward, we need to be able to generate a flame graph based on just the samples of a profile and its locations.
More tests will be either in this PR or following PRs to match the existing `flamegraph_test.go`, up to the reviewer.
=> pkg/storage: Implement GenerateFlamegraphFlat that works based on []Sample

pkg/query/query.go
We had a few reports that their logs were spammed with "timestamp is 0" and to mitigate this, we can rather `break` than `continue`. The downside might be that you won't see any metrics if it's the first sample or in between, that's `0`. So far when I saw this happening it was always the last sample tough, so we can stop anyway.
=> Break query loop when timestamp 0

pkg/parca/parca.go, pkg/profilestore/profilestore.go, pkg/query/query.go, pkg/query/query_test.go, pkg/storage/benchmark/db-appends.txt, pkg/storage/benchmark/db-iterator.txt, pkg/storage/benchmark_test.go, pkg/storage/db.go, pkg/storage/db_test.go, pkg/storage/diff.go, pkg/storage/flamegraph_flat.go, pkg/storage/flamegraph_flat_test.go, pkg/storage/head.go, pkg/storage/interface.go, pkg/storage/merge.go, pkg/storage/profile_flat.go, pkg/storage/profile_flat_test.go, pkg/storage/querier_bench_test.go, pkg/storage/series.go, pkg/storage/series_iterator.go, pkg/storage/series_iterator_merge_test.go, pkg/storage/series_iterator_range.go, pkg/storage/series_iterator_range_test.go, pkg/storage/series_iterator_root.go, pkg/storage/series_iterator_root_test.go, pkg/storage/series_test.go, pkg/symbolizer/symbolizer_test.go
Implement querying the new, more simple, `[]*Sample` from the QueryRange and Query.singleProfile handlers.
For now, we pass a `profileTrees` bool into some structs to decide whether or not to use the new storage or old storage way of representing trees. Eventually, we'll clean it up by removing the profileTree entirely.
=> pkg/storage: Querying flat profiles

pkg/storage/benchmark/db-appends.txt, pkg/storage/benchmark/db-iterator.txt, pkg/storage/metastore/badger.go, pkg/storage/profile_flat.go, pkg/storage/profile_normalizer.go, pkg/storage/profile_normalizer_test.go, pkg/storage/profile_tree.go, pkg/storage/series.go, pkg/storage/series_iterator.go, pkg/storage/series_iterator_range.go, pkg/storage/series_test.go
StacktraceKey benchmarks: :tada: 
```
name                  old time/op    new time/op    delta
MakeStacktraceKey-24    2.07µs ± 1%    0.37µs ± 6%   ~     (p=0.100 n=3+3)
name                  old alloc/op   new alloc/op   delta
MakeStacktraceKey-24      625B ± 0%      192B ± 0%   ~     (p=0.100 n=3+3)
name                  old allocs/op  new allocs/op  delta
MakeStacktraceKey-24      22.0 ± 0%       5.0 ± 0%   ~     (p=0.100 n=3+3)
```
DB Appends: :thinking: 
```
name        old time/op    new time/op    delta
Appends-24    16.8ms ± 1%    23.2ms ± 1%   ~     (p=0.100 n=3+3)
name        old alloc/op   new alloc/op   delta
Appends-24    9.84MB ± 0%   11.81MB ± 0%   ~     (p=0.100 n=3+3)
name        old allocs/op  new allocs/op  delta
Appends-24      140k ± 0%      149k ± 0%   ~ …
```
=> pkg/storage: Make stacktraceKey []byte and use inlined map[string]

pkg/storage/benchmark/db-appends.txt, pkg/storage/benchmark/db-iterator.txt, pkg/storage/diff.go, pkg/storage/flamegraph_flat.go, pkg/storage/flamegraph_flat_test.go, pkg/storage/interface.go, pkg/storage/merge.go, pkg/storage/metastore/badger.go, pkg/storage/profile_flat.go, pkg/storage/profile_normalizer.go, pkg/storage/profile_normalizer_test.go, pkg/storage/profile_tree.go, pkg/storage/series.go, pkg/storage/series_iterator.go, pkg/storage/series_iterator_range.go, pkg/storage/series_iterator_root.go, pkg/storage/series_test.go
This PR depends on #448 
```
name        old time/op    new time/op    delta
Appends-24    23.2ms ± 1%    21.5ms ± 3%   ~     (p=0.100 n=3+3)
name        old alloc/op   new alloc/op   delta
Appends-24    11.8MB ± 0%    10.3MB ± 0%   ~     (p=0.100 n=3+3)
name        old allocs/op  new allocs/op  delta
Appends-24      149k ± 0%      136k ± 0%   ~     (p=0.100 n=3+3)
```
```
name         old time/op    new time/op    delta
Iterator-24    60.0µs ± 1%    66.9µs ± 9%   ~     (p=0.100 n=3+3)
name         old alloc/op   new alloc/op   delta
Iterator-24      490B ± 0%      496B ± 1%   ~     (p=0.100 n=3+3)
name         old allocs/op  new allocs/op  delta
Iterator-24      3.00 ± 0%      3.00 ± 0%   ~     (all equal)
```
Overall I'm surprised this entire endeavor of moving from stacktraceKey as …
=> pkg/storage: Use map[string]*Profile in storage

pkg/query/query.go, pkg/storage/head.go, pkg/storage/interface.go, pkg/storage/merge.go, pkg/storage/merge_flat_test.go, pkg/storage/merge_test.go, pkg/storage/series_iterator_merge_test.go
It's fast. So fast, I literally can't tell the difference between a single profile and a merge profile anymore right now (on my machine with a couple of minutes of profiles :smile:) :rocket: 
```
name              old time/op    new time/op    delta
MergeMany/1-24      99.3µs ± 2%    26.7µs ± 2%   ~     (p=0.100 n=3+3)
MergeMany/2-24       306µs ± 3%      52µs ± 1%   ~     (p=0.100 n=3+3)
MergeMany/4-24       632µs ± 7%      99µs ± 2%   ~     (p=0.100 n=3+3)
MergeMany/8-24      1.30ms ± 3%    0.18ms ± 2%   ~     (p=0.100 n=3+3)
MergeMany/16-24     2.80ms ± 2%    0.34ms ± 2%   ~     (p=0.100 n=3+3)
MergeMany/32-24     5.61ms ± 3%    0.63ms ± 1%   ~     (p=0.100 n=3+3)
MergeMany/64-24     11.1ms ± 2%     1.1ms ± 4%   ~     (p=0.100 n=3+3)
MergeMany/128-24    22.3ms ± 1%     2.1ms ± 3%   ~ …
```
=> pkg/storage: Implement merging of flat profiles

pkg/storage/diff.go, pkg/storage/diff_flat_test.go, pkg/storage/diff_test.go, pkg/storage/flamegraph_flat.go, pkg/storage/profile_normalizer.go
Comparing apples and oranges once more, but diffing for flat profiles is looking good:
```
name            old time/op    new time/op    delta
Diff/simple-24     118µs ± 8%       5µs ±10%  -95.72%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
Diff/simple-24     117kB ± 0%       2kB ± 0%  -98.04%  (p=0.000 n=10+10)
name            old allocs/op  new allocs/op  delta
Diff/simple-24     2.43k ± 0%     0.01k ± 0%  -99.79%  (p=0.000 n=10+10)
```
=> pkg/storage: Implement diffs for flat profiles

pkg/storage/series.go, pkg/storage/series_test.go
We should truncate these to support proper retention for flat profiles too.
=> pkg/storage: Truncate flat profile chunks

pkg/storage/flamegraph_flat.go, pkg/storage/flamegraph_flat_test.go
The key difference to the previous implementation now is, that we always get the nodes for a location first.
Then, then we loop over these and in turn also inline the functions properly. That way handling the inlined functions that aren't yet part of the flame graph are exactly the same as handling inline functions that already exist in the flame graph.
=> Correct inline existing functions in flamegraphs

pkg/storage/benchmark/db-appends.txt, pkg/storage/benchmark/db-iterator.txt, pkg/storage/flamegraph_flat.go, pkg/storage/flamegraph_flat_test.go, pkg/storage/metastore/badger.go, pkg/storage/metastore/inmemory_sqlite.go, pkg/storage/metastore/metastore.go, pkg/storage/metastore/ondisk_sqlite.go, pkg/storage/metastore/remote.go, pkg/storage/series_iterator.go
This should allow us to remove the labels from the storage entirely going forward, where they don't really belong anyway.
In the end we don't even use the labels in the flame graph, maybe we should start doing something with them? https://github.com/parca-dev/parca/issues/488
Appends:
```
name        old time/op    new time/op    delta
Appends-24    28.3ms ± 2%    27.7ms ± 2%    ~     (p=0.056 n=5+5)
name        old alloc/op   new alloc/op   delta
Appends-24    11.3MB ± 0%    11.4MB ± 0%  +0.55%  (p=0.008 n=5+5)
name        old allocs/op  new allocs/op  delta
Appends-24      162k ± 0%      164k ± 0%  +1.59%  (p=0.008 n=5+5)
```
Iterator:
```
name         old time/op    new time/op    delta
Iterator-24    62.3µs ±13%    73.8µs ±15%  +18.51%  (p=0.032 n=5+5)
name         old alloc/op   new …
```
=> pkg/storage: Use metastore for storing and retreiving stacktraces by UUID

ui/packages/app/web/src/components/MetricsGraph.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph.tsx, ui/packages/shared/profile/src/ProfileView.tsx
This adds a reset view button for the icicle graphs. I opted for "Reset View" as the text but let me know if you have other ideas.
This also fixes the weird behaviour with the download pprof button and the metrics tooltip. The latter would display underneath the button.
This resolves #474
**Screenshot**
=> Add a reset view button to Icicle graphs

Makefile
The default shell Make will try to use in /bin/sh which does not
implement the `source` command, causing make targets such as `dev/up` to
fail.
=> *: Specify shell in Makefile

env.sh
There was a `mv` command omitted in the script which caused it to try
running the `minikube-linux-amd64` binary instead of moving it into
$PATH. This caused an error because the binary would not be found.
Add `mv` command to fix this.
=> *: Fix env.sh when installing minikube

ui/packages/app/web/package.json, ui/packages/app/web/tailwind.config.js, ui/yarn.lock
This PR adds a commit on top of #491, to port the `tailwind.config.js` to eliminate a deprecation warning during the startup.
=> Tailwind v3 upgrade

pkg/parca/parca.go
Time to use the slimmer version of the storage that doesn't use profile trees anymore. 
I still want to keep the hidden flag, just in case we encounter problems, and can point people to turning profile trees on again.
=> pkg/parca: Don't use profileTrees by default anymore

pkg/storage/series_iterator.go, pkg/storage/series_iterator_range.go, pkg/storage/series_iterator_range_test.go
We currently don't seek the correct index for samples in chunks. 
This has the effect that we basically every only read the first sample of each chunk - resulting in not updating icicle graphs until a timestamp in another chunk is selected.
I was already wondering why this was happening in the UI... :man_shrugging: :smile:
=> pkg/storage: Fix bug so samples seek to correct index

Dockerfile, Makefile
We added the version to binaries compiled outside containers but were still missing the version and commit for the container binaries.
This PR add VERSION and COMMIT to Parca so that it shows up in the UI too.
=> Add version and commit to Parca build in container

.github/workflows/container.yml, Dockerfile, Makefile
At this time, this adds additional support for arm64-based containers.
This can be useful for cloud-based platforms like graviton or to run
parca at home on your SBC cluster.
TODO: Still needs verification that the CI path works and actual testing on an arm64 board.
=> [WIP] Add support for multi-arch container builds

Makefile
@brancz  This should allow to push all architectures.
currently it only pushed one image.
=> Makefile: Push manifest instead of image

pkg/query/flamegraph_flat.go, pkg/query/flamegraph_flat_test.go
Fixes #578
For some reason, we didn't set the unit field anymore. :man_shrugging: 
It might be easier to construct the struct in the workflow I chose now and similar mistakes could be easier to catch. Either way, I added updated a unit test too to catch it in the future.
=> pkg/query: Fix adding a unit to the flamegraph

pkg/scrape/scrape.go
Logs are being swallowed currently because no errc is provided by the
scrape loop.
We should log the errors if not errc is provided.
=> Log error if no err channel provided

ui/packages/app/web/src/components/ProfileExplorer.tsx, ui/packages/app/web/src/components/ProfileExplorerCompare.tsx, ui/packages/app/web/src/components/ProfileExplorerSingle.tsx, ui/packages/app/web/src/components/ProfileSelector.tsx, ui/packages/app/web/src/components/ui/CloseIcon.tsx
Closes #211 
https://user-images.githubusercontent.com/52544819/151407091-d6f30235-060a-4ad7-8a91-e279b75a43ab.mp4
The `compare_a` parameter continues to exist in the single profile view. If necessary, I can write another function that will filter the params based on the prefix(`compare_` in this case).
=> Close profile card in compare view

pkg/query/query_test.go
Hopefully, this will cut the flaky test some slack, and using UTC should make any CI differences negligible.
Fixes #499
=> pkg/query: Fix flaky Test_QueryRange_Limited by increasing timeouts and using UTC

pkg/columnstore/granule.go, pkg/columnstore/part.go, pkg/columnstore/table.go, pkg/columnstore/table_test.go
Read locks on the index on insert and then writer locks on the granules themselves.
Write locks on the index when during splits.
=> Adds lower level locking to the column store.

.github/workflows/go.yml, .github/workflows/golangci-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/proto.yml, .github/workflows/ui.yml
Especially for golangci-lint, proto and jsonnet we don't need to run these actions, if none of the related files changed.
As for the UI and Go itself I'm not 100% sure but willing to try. Maybe doing a change to the README would be super fast then? Not sure if those are worth it in the end. WDYT?
=> Only run GitHub Actions when related files changed

pkg/server/server.go, ui/packages/app/web/src/pages/index.tsx
This allows us to also simply put `/api` in front of API requests and still get the correct resources served. It seems as if [grpcweb.WithAllowNonRootResource](https://github.com/improbable-eng/grpc-web/blob/7dc90821e5bbaae7ff8c2386f72d59653d0fb169/go/grpcweb/options.go#L164-L168) simply truncates any prefix and basically matches the endings. The actual stripping of the prefix happens in [getGRPCEndpoint](https://github.com/improbable-eng/grpc-web/blob/7dc90821e5bbaae7ff8c2386f72d59653d0fb169/go/grpcweb/helpers.go#L43-L50).
For now I added `/api` as prefix in the frontend queryClient but we could also go with `/grpc` instead. Whatever people feel is better.
Closes #614 
Unblocks #598
=> Add support for non-root-prefixes for grpc-web

pkg/config/config.go, pkg/config/config_test.go
Hello there 👋, what an exciting project you have here!
I just started pocking around with Parca, and I hit this little bug on a define `profiling_config`, but empty `{}`, so not `nil`:
<details>
<summary>logs</summary>
```
ooooooooo.
`888   `Y88.
888   .d88'  .oooo.   oooo d8b  .ooooo.   .oooo.
888ooo88P'  `P  )88b  `888""8P d88' `"Y8 `P  )88b
888          .oP"888   888     888        .oP"888
888         d8(  888   888     888   .o8 d8(  888
o888o        `Y888""8o d888b    `Y8bod8P' `Y888""8o
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc002c9fa20)
gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x8d
panic(0x3236b20, 0x3e82970)
runtime/panic.go:965 +0x1b9 …
```
=> fix(config): Fix panic on empty profiling_config

deploy/grafana/parca.json
The template name had likely been overwritten by the Grafana export.
I have done that so many times, I have written scripts a couple years ago, now in a Gist if that helps anyone:
https://gist.github.com/maxbrunet/e96dee35f7e5fcd73a98929f4bc9c2bb
=> fix(grafana): Fix datasource template

deploy/grafana/parca.json
Update the Grafana dashboard PromQL queries to add `sum by()` to not pollute the panels with the amount of labels.
=> deploy: Update PromQL queries in Grafana dashboard

ui/packages/app/web/src/components/ui/DateTimePicker/index.tsx, ui/packages/app/web/src/components/ui/DateTimeRangePicker/DateTimeRangePickerPanel/AbsoluteDatePicker/index.tsx, ui/packages/app/web/src/components/ui/DateTimeRangePicker/utils.ts, ui/packages/shared/functions/src/index.ts
Fixes #663.
Added a small note as well to indicate it is in UTC:
=> ui/datePicker: Date Range Picker uses UTC as the timezone

deploy/lib/parca/parca.libsonnet
We now have arm64 and further builds for other architectures so this is no longer a requirement.
=> deploy: Remove amd64 node requirement

ui/packages/app/web/src/components/ProfileExplorer.tsx
Fixes #662
Two things were responsible for the bug here. The query parameter  `expression_a` was being interpreted as an array whenever there are multiple labels and it was not being encoded. This PR checks if the query param is an array, if it is, it converts it to a string and then encodes them in the fns for selecting profiles and queries.
=> area/ui: Fix selecting multiple labels breaking the UI

.github/workflows/publish.yml
`yarn bootstrap` runs the command `lerna bootstrap` which install all dependencies and links any cross-dependencies which isn't a needed step in the Publish action. It can also lead to errors like [this](https://github.com/parca-dev/parca/runs/5389939995?check_suite_focus=true) so it's best to remove the step entirely.
=> area/ui: Remove Bootstrap step in publish.yml file

pkg/parca/parca.go, pkg/profilestore/grpc.go
If there is a central place (cluster) to store profiles we still might want to collect pprof profiles and then forward them via gRPC as written in #629. 
To be able to do that we now support a `--mode=scraper` (instead of the current only `--mode=all`). 
Possibly making this a sub command instead of just a flag might be better. 
The UI is broken in --mode=scraper as only the API for the Targets page is available. We should hide the "Profiles" page in that case. Most likely we'll need to communicate the mode from the backend to the frontend for that to happen.
Closes #629
=> pkg/profilestore: Add a Parca scraper-only mode that forwards via gRPC

deploy/dev.jsonnet, deploy/lib/parca/parca.libsonnet, pkg/debuginfo/debuginfod.go, pkg/debuginfo/store.go, pkg/debuginfo/store_test.go, pkg/parca/parca.go, pkg/symbolizer/symbolizer_test.go
- Optimize fetching objects from debuginfod server
- Previously it was downloading from public server and uploading to object store then downloading again to utilize the object file.
- Right now it caches the downloaded file to local filesystem and asynchronously uploads it to object store.
- Add the ability to specify multiple servers
- Add jsonnet config generators for debuginfod configurations
- Prevents actual requests to debuginfod servers while testing
=> debuginfo: Fix several issues with debuginfod client

ui/packages/app/web/src/pages/layouts/Component404.tsx, ui/packages/app/web/src/pages/targets.tsx, ui/packages/app/web/tailwind.config.js, ui/packages/shared/components/src/EmptyState/index.tsx, ui/packages/shared/components/src/index.tsx
resolves #669 
Creates a reusable EmptyState container component in the shared folder, which can be used throughout the application as a placeholder when data is not available
=> feat: empty state container for targets page

pkg/profile/profile.go, pkg/profile/profile_flat.go, pkg/profile/profile_flat_test.go, pkg/profilestore/profilestore.go, pkg/query/flamegraph_flat.go, pkg/query/flamegraph_flat_test.go, pkg/query/pprof_test.go, pkg/query/query_test.go, pkg/query/top_test.go, pkg/storage/benchmark_test.go, pkg/storage/db.go, pkg/storage/db_test.go, pkg/storage/diff_flat_test.go, pkg/storage/head.go, pkg/storage/head_read_test.go, pkg/storage/head_test.go, pkg/storage/interface_test.go, pkg/storage/merge.go, pkg/storage/merge_flat_test.go, pkg/storage/querier_bench_test.go, pkg/storage/series.go, pkg/storage/series_iterator_range.go, pkg/storage/series_iterator_range_test.go, pkg/storage/series_iterator_root.go, pkg/storage/series_iterator_root_test.go, pkg/storage/series_test.go
Closes #608
Please let me know if there's any contributing guideline I missed. I had some confusion regarding repo forks that I mentioned in [an issue](https://github.com/parca-dev/parca/issues/707#issuecomment-1058937048), but I've gone ahead with forking this repo, adding the remote, pushing to it, and opening the PR here.
In this commit, I've only refactored the `FlatProfile` struct to `Profile` and wherever it's used. There are still some places which include the name `FlatProfile`, shall I refactor them as well? This would also involve removing the [InstantFlatProfile interface](https://github.com/parca-dev/parca/blob/8ad0e103287156104c4bd0d977efc64fdbbf8056/pkg/profile/profile.go#L59), as there is already an `InstantProfile` interface with the same methods.
=> pkg: Rename FlatProfile to Profile

.github/workflows/release.yml, .goreleaser.yml, Dockerfile.release
* ~Goreleaser uses docker buildx to build images~ Unfortunately, it's still not possible to use docker for reproducible builds. And Goreleaser only supports podman with pro version, for full build pipeline transparency we don't want to use pro version for Parca. I still want to keep the configs around until we figure out how to achieve this using goreleaser.
ref #762
=> Refine goreleaser config for reproducible builds

pkg/debuginfo/store.go, pkg/hash/hash.go, pkg/symbol/symbol.go
Abide org wide conventions
Fix for the following error:
`level=debug ts=2022-03-25T07:46:41.299687467Z caller=upload.go:100 component=debuginfo component=uploader msg="failed to upload debug information" buildid=5f2f484bf4ee5db1 path=tmp/5f2f484bf4ee5db1/debuginfo retry=1.155145846s err="send upload info: rpc error: code = Internal desc = grpc: error while marshaling: string field contains invalid UTF-8"`
=> hash: Fix hash encoding issue

ui/packages/shared/components/src/DateTimeRangePicker/DateTimeRangePickerPanel/RelativeDatePicker/index.tsx
It's possible to end up in this state. We should prevent that.
=> ui: Time Picker relative time ranges need to be positive

ui/packages/app/web/src/pages/targets.tsx
The most important change in this PR is the fact that the targets for a job are now sorted by their URL. 
Sometimes, for debugging, I frequently reload the targets page, and not having the tables sorted makes it hard to follow what's going on.
Additionally, I've made the headline of each job bigger.
cc @monicawoj
=> ui: Sort Targets by URL, make job name bigger

ui/packages/shared/components/src/MatchersInput/index.tsx
I'm not sure if these matcher input labels are so squared on purpose, but they somehow don't fit the rest of the UI all being rounded. 
The left one is how it currently looks and the right is my change.
=> ui: Add rounded MatcherInput labels

pkg/query/query.go, pkg/query/query_test.go
This should get rid of all empty (meaning the cumulative value is zero) such that we don't even send metadata along for those nodes.
=> pkg/query: Add stripEmptyNodes helper for flamegraphs

pkg/query/top.go
This sorts the list by the meta location address, so the flaky `TestAggregateTopByFunction` passes every time. (#770)
I ran the test multiple times without any changes, and encountered 2 types of failures: `UniqueFunction` and `UniqueAddress`.
<details>
<summary>Logs for failing `UniqueFunction` test</summary>
<br>
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestAggregateTopByFunction$ github.com/parca-dev/parca/pkg/query
--- FAIL: TestAggregateTopByFunction (0.00s)
--- FAIL: TestAggregateTopByFunction/UniqueFunction (0.00s)
/home/ujjwal/oss/parca-dev/parca/pkg/query/top_test.go:300: 
Error Trace:	top_test.go:300
Error:      	Not equal: 
expected: &queryv1alpha1.Top{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, …
=> Fix flaky 'TestAggregateTopByFunction`

pkg/query/top.go
Follow-up PR after discussion in #847. Sorts by descending flat value by default, but if flat value is same, sorts by ascending meta location address (this second case is needed currently for the tests to pass every time).
=> pkg/query: Sort list in aggregateTopByFunction

deploy/main.jsonnet, deploy/openshift.jsonnet
It removes k8s namespace duplicates as advised in #871.
```sh
$ go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest
$ go install github.com/brancz/gojsontoyaml@latest
$ cd ./deploy/
$ make manifests
```
<details>
<summary>kubernetes</summary>
```yaml
apiVersion: v1
data:
parca.yaml: |-
"debug_info":
"bucket":
"config":
"directory": "./tmp"
"type": "FILESYSTEM"
"cache":
"config":
"directory": "./tmp"
"type": "FILESYSTEM"
kind: ConfigMap
metadata:
name: parca-config
namespace: parca
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app.kubernetes.io/component: observability
app.kubernetes.io/instance: parca
app.kubernetes.io/name: parca
app.kubernetes.io/version: ns-dupl-8f3de8f9
name: parca
namespace: parca
spec:
replicas: 1
selector:
matchLabels: …
```
=> Remove k8s namespace duplicate

env.sh
Currently we download the x86 binaries even on arm, let's fetch
the `tilt` + `minikube` binaries for the matching architecture
Had to bump `ctlptl` to 0.5.1 as they started generating the arm64
builds starting that version. Changes between [v0.5.0-v0.5.1](https://github.com/tilt-dev/ctlptl/compare/v0.5.0...v0.5.1)
**Test plan**:
```shell
$ ./env.sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
35 68.2M   35 24.4M    0     0  6040k      0  0:00:11  0:00:04  0:00:07 6039k^C
[vagrant@bazinga parca]$ ./env.sh
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 68.2M  100 68.2M    0     0  6127k      0  0:00:11  0:00:11 --:--:-- 6057k
+ tar …
```
=> env.sh: add support for arm64

pkg/profilestore/profilestore.go, pkg/profilestore/profilestore_test.go
=> Validate labels for profiles received from agent

pkg/symbol/demangle/demangle.go, pkg/symbol/demangle/demangle_test.go
Saw that @kakkoyun opened an issue to add Rust demangling support
(https://github.com/parca-dev/parca/issues/612) and was going to add another
library or implement it myself, but noticed that [the library we are currently
using for C++ demangling](https://github.com/ianlancetaylor/demangle) already supports the Rust mangling scheme!
Happy days!
This PR updates the comment in `demangle.go` and adds some unit tests for the
demangler to make sure we don't regress on basic functionality and set ups
the file for further testcases once we expand the languages we support.
Have decided to create independent test cases as I think it's more readable and
easier to understand, but happy to change it if you would rather use parametric
tests.
Please, let me know if you have any feedback!
Note: …
=> demangler: add tests for the Cpp and Rust demanglers

pkg/profilestore/profilecolumnstore.go
Labelsets can contain `/` so we need to encode the directory names
appropriately.
=> pkg/profilestore: Encode debug log paths

pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/pprof.go, pkg/query/top.go
Previously we had a fast path for pre-processing diffs that are
identical. It turns out that this fast path messed up the data and was
hiding that some diffs were not done correctly. This primarily happened
when non-merged different binaries are compared.
cc @roidelapluie
=> pkg/query: Fix diffing for distinct stacktraces

go.mod, go.sum
With this change, Parca server actually becomes go-install/get-able 🎉
=> go.mod: Update arcticdb and remove replace directives

pkg/query/columnquery.go, pkg/query/query.go, pkg/query/top.go, pkg/query/top_test.go
Previously we were only setting the flat value when we see the leaf for the first time, but it's possible that the same function occurs in many leafs, thus it's "cumulative flat value" is different. It also meant that whatever the first leaf value was that we saw was the one used. With this patch they are now correctly summed up.
@metalmatze
=> pkg/query: Fix incorrect aggregation of flat values in table

pkg/query/columnquery.go
Signed-off-by: Ben Ye <ben.ye@bytedance.com>
`seen` set is not needed because there is already a distinct operator in the logical plan.
=> remove deduplicate set when distinct is enabled

ui/packages/app/web/src/style/profile.css, ui/packages/app/web/tailwind.config.js, ui/packages/shared/profile/src/IcicleGraph.tsx, ui/packages/shared/profile/src/TopTable.tsx
This PR updates the fonts used in the Parca UI and also uses softer colors for the Icicle graph. 
The Icicle graph and Top table now use the `Roboto Mono` font and I also decided to update the main font being used in the UI to be `Poppins` since that's the font used in the upcoming Parca website redesign.
Resolves #877 
Some screenshots:
and because it looks so gooood in **light mode**:
=> area/ui: Update fonts in the UI

ui/packages/shared/components/src/DateTimeRangePicker/utils.ts
Whenever a new query is started, the range key of the query is
undefined, so we need to be able to handle that state.
=> ui: Gracefully handle undefined range keys

Makefile, go.mod, go.sum, pkg/debuginfo/debuginfod.go, pkg/debuginfo/debuginfod_test.go
The library used: ~https://github.com/sebdah/goldie~ https://github.com/dnaeon/go-vcr (goldie needs https://pkg.go.dev/net/http/httptest#ResponseRecorder which is useful when you test against your own server. Unfortunately, in this case we need to request to an external service. One alternative would be to create a proxy and use `ResponseRecorder `but I think it won't worth the hassle, so I used the go-vcr package directly.)
About golden test files: https://www.youtube.com/watch?v=yszygk1cpEc
=> debuginfod: Fix tests depends on external service

pkg/config/config.go, pkg/config/config_test.go
It seems I may have misunderstood the issue. 
Looking at the 2 configs in the issue description, I thought it meant discovering pprof configs (from somewhere) once the user has specified a particular prefix. However, from [this comment](https://github.com/parca-dev/parca/issues/931#issuecomment-1117506666) I realise it means not having to write a particular string repeatedly while specifying multiple configs. If it is the second case that needs to be addressed, this PR should be good.
Need help understanding relabelling though and what it means in the context of this issue.
=> pkg/config: Support prefix for pprof config (#931)

scripts/make-containers.sh
Hi! There is a critical vulnerability (CVE-2022-28391) in 3.15.0, see https://snyk.io/test/docker/alpine:3.15.0.
The latest version 3.15.4 addressed the issues.
=> Upgrade alpine from 3.15.0 to 3.15.4

.github/workflows/docs.yml, .github/workflows/go-build-test.yml, .github/workflows/go-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/proto-gen.yaml, .github/workflows/proto-pr.yaml, .github/workflows/proto-push.yaml, .github/workflows/release-dry-run.yml, .github/workflows/release.yml, Dockerfile.dev, Dockerfile.go.dev, Dockerfile.release, proto/buf.lock, scripts/make-containers.sh
- update go in the actions and use the recommended way to get the latest
- update go base image to 1.18.2
=> Update go to use 1.18.2

.github/workflows/container.yml, .github/workflows/release.yml, Makefile
was trying to debug and reproduce locally but could not find why podman is giving a different digest from the image that is pushed to the registry. 
job that failed https://github.com/parca-dev/parca/actions/runs/2321776702
So I propose to use the crane tool (https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md) which is a nice and simple tool to manage easily the container.
if the maintainers agree I can open the PR in the other repo to use the same approach
a sample successfully run in my fork https://github.com/cpanato/parca/runs/6434708198?check_suite_focus=true
and checking the signature
```
$ cosign verify ghcr.io/cpanato/parca:test-4ddfa1ce | jq . | pbcopy
Verification for ghcr.io/cpanato/parca:test-4ddfa1ce --
The following checks were performed on each …
```
=> use crane to get the container digest to use to sing it

README.md
Link had a '/' in the end due to which the page was giving 404.
=> readme: fix eBPF profiler link

env-local-test.sh
The above file did not have executable permission so when running `make
dev/setup` it failed.
For `amd64` arch `ctlptl` releases use `arch_uname` in the link. Fixed
it so that file work correctly. For more information check
https://github.com/tilt-dev/ctlptl/releases/tag/v0.5.1
=> env-local-test.sh: Fix file format and ctlptl link

pkg/config/config.go, pkg/parca/parca.go
parca was not able to load the config file correctly due to which yaml
testing was not done correctly. This fixes it.
`job_name` config should be mandatory for prometheus `scrape_config`.
Fixes: #929
=> config: parca starts by testing valid config

ui/packages/shared/components/src/DateTimeRangePicker/DateTimeRangePickerTrigger.tsx
This PR ensures that the date time text in the `DateTimePicker` is truncated whenever it gets too long. This happened especially when using the absolute version of the date picker and gave the `MatchersInput` search box extra height.
Before
After
=> area/ui: Truncate date-time text when it overflows

README.md
Fixes the broken link reported in https://github.com/parca-dev/parca/issues/1070
This is probably not the correct fix, however I'm not familiar with the docs engine you are using so I was not able to provide a fix there instead.
=> Fix storage docs link

pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/parca/testdata/parca.yaml, pkg/parcacol/arrow.go, pkg/parcacol/ingest.go, pkg/parcacol/ingest_test.go, pkg/parcacol/parcacol.go, pkg/parcacol/sample.go, pkg/profilestore/profilecolumnstore.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go
WriteRaw requests have been the bottleneck in the last weeks as profiles have shown.
Since the migration to columnar storage we don't need the FlatProfiles anymore and now convert pprof profiles into columnar rows directly. 
```
name          old time/op    new time/op    delta
_WriteRaw-24     1.03s ± 2%     0.95s ± 3%   ~     (p=0.100 n=3+3)
name          old alloc/op   new alloc/op   delta
_WriteRaw-24    3.28GB ± 2%    2.97GB ± 4%   ~     (p=0.100 n=3+3)
name          old allocs/op  new allocs/op  delta
_WriteRaw-24     3.56M ± 0%     3.47M ± 0%   ~     (p=0.100 n=3+3)
```
Two things are missing for this to be merged:
=> pkg/parcacol: Create a pprof ingester that converts to row directly

.github/workflows/container.yml, Dockerfile, scripts/make-containers.sh
To run arm64 arch, QEMU is used. `qemu binfmt-support` packages are
required qemu dependency.
While building container images for arm64 the network is slow due to
container in container mode and yarn install fails if the packages are
big as default retry timeourt is 30sec. Increasing it fixes the issue.
=> actions: Fix build and push job for arm64

.github/workflows/go-build-test.yml, Makefile, pkg/query/columnquery_test.go
Added support for arm64 architecture. A new docker container with
`arm64v8/ubuntu` image is spawned using QEMU.
`yarn install` is slow on arm64 container in container mode. So
installing yarn packages in amd64 ubuntu machine and mounting it while
running docker container.
Fixes: #562 
=> Multi arch testing support for CI

README.md, pkg/parca/parca.go
These flags are no longer valid since we've moved to arcticdb as the only option.
=> removes deprecated flags since switch to arcticdb

ui/packages/shared/profile/src/IcicleGraph.tsx
As spotted by @/kura on [Discord](https://discord.com/channels/877547706334199818/877547706334199821/981906552095146034), the Icicle graph seemed to not show up at all on Firefox browsers.
After investigating a bit, I modified the IcicleGraph's component `svg` element to get its width & height from the respective width and height property as opposed to using the `viewBox` property and that makes the graph show up now in the Firefox browser. I also did a test across different browsers to ensure it works.
Fixes #1130
=> area/ui: Fix the Icicle graph bug for Firefox browsers

pkg/query/columnquery.go
If a query does not contain a `__name__` label this code would have previously panicked.
Now there won't be a panic, but the error in line 208 would actually be returned.
Fixes #1134
=> Fix panic if QueryRange doesn't contain __name__

go.mod, go.sum, pkg/debuginfo/debuginfod.go, pkg/debuginfo/store.go
with `go get
github.com/polarsignals/arcticdb@19ee1150985463844e886746966d12e8fffdb8df`.
And update objstore's usage to the new API which changed in
https://github.com/thanos-io/objstore/commit/c4f11442aa33a5b8c1948e6d43b659aac62ad425
Changes between commits: https://github.com/polarsignals/arcticdb/compare/4e2f5c4b210e...19ee1150985
=> Upgrade arcticdb to the latest version

pkg/debuginfo/store.go
Instead, we will ask the client to upload their debuginfo once more.
=> Ignore io.EOF errors when checking dwarf from objstore

ui/packages/shared/components/src/DateTimeRangePicker/DateTimeRangePickerPanel/RelativeDatePicker/index.tsx
Also make 15min the default.
I've never used the 3 days time range, however I often find myself typing 5 or 10 min into the time range picker. 15min is probably totally fine, and thus went with that. 
It's more helpful for the deployments of Parca we currently have, until we have actual persistence and long term storage, then we should discuss the time ranges again.
=> ui: Add last 15min to DateTimeRangePicker

env.sh, pkg/debuginfo/metadata.go, pkg/debuginfo/metadata_test.go, pkg/debuginfo/store.go
At the moment, debug files are uploaded to our gRPC server by [streaming](https://github.com/parca-dev/parca/blob/2af5503bba08b709eaf07a3b83b18c9bc29cd262/pkg/debuginfo/reader.go#L34) its chunks. [Once we receive all the chunks](https://github.com/parca-dev/parca/blob/e0c7d0cf16275d30591a93a373c292683efab360/pkg/debuginfo/client.go#L54), we write the whole file in blob storage.
Right now there's no metadata associated with said debug files. Adding metadata to the uploads would allow us, among other things, to:
- debug issues more easily, as we can add extra data to uploads
- add new features in the future (such as different debug formats), and many more
Another welcomed effect is that, while this doesn't eliminate Upload() race conditions, it heavily reduces their likelihood. 
Imagine two …
=> Add Debuginfo metadata

pkg/query/columnquery.go, pkg/query/columnquery_test.go
In https://github.com/parca-dev/parca/issues/1121 @brancz suggested to change `timestamp column not found` error to be handled differently.
I am not sure how exactly it should be handled, so at least here is a test case to start a conversation :)
=> Better error handling when db result is empty

Dockerfile, Dockerfile.dev, Dockerfile.go.dev, scripts/make-containers.sh
Same changes as parca-dev/parca-agent#465 +:
* Pin `grpc-health-probe` version for reproducible builds
* Use `podman build` with `--platform` instead of `--arch`, so global `BUILD*`/`TARGET*` args are set and cache behaves properly
I do not know a way to backtrack a manifest list from a digest since the tag has moved, so base images have been updated
=> build: fix silent container build failure and lint

.github/workflows/go-build-test.yml
Fixes
```
Ign:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 qemu amd64 1:4.2-3ubuntu6.21
Ign:2 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 qemu-user-static amd64 1:4.2-3ubuntu6.21
Err:1 http://azure.archive.ubuntu.com/ubuntu focal-updates/main amd64 qemu amd64 1:4.2-3ubuntu6.21
404  Not Found [IP: 40.81.13.82 80]
Err:2 http://azure.archive.ubuntu.com/ubuntu focal-updates/universe amd64 qemu-user-static amd64 1:4.2-3ubuntu6.21
404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/q/qemu/qemu_4.2-3ubuntu6.21_amd64.deb  404  Not Found [IP: 40.81.13.82 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_4.2-3ubuntu6.21_amd64.deb  404  Not Found [IP: …
```
=> ci: ensure package index is up-to-date before installing qemu

.github/workflows/publish-ui.yml
Attempting a fix to Lerna publish issue on the GitHub action here: https://github.com/parca-dev/parca/runs/7087395220?check_suite_focus=true
=> ui: Checking out the main branch before publish

.github/workflows/go-build-test.yml
Fixes:
```
/home/runner/.cache/go-build
Error: There are no cache folders on the disk
```
=> ci: disable setup actions on arm64

.github/workflows/jsonnet.yml, .github/workflows/proto-gen.yaml, .github/workflows/proto-pr.yaml, .github/workflows/proto-push.yaml
To prevent failures like https://github.com/parca-dev/parca/runs/7109360855?check_suite_focus=true
=> chore: Disable Go cache for non-project dependencies

.golangci.yml
github.com/segmentio/parquet-go  uses generics
=> chore: Disable problematic linters (caused by generics)

buf.gen.yaml, proto/buf.lock, renovate.json
Because we certainly can. It will be a bit clunky though, as the Git tags do not match one-to-one with Buf tags and Renovate will not be able to run `buf generate`. It should at least avoid having to keep an eye out for releases. `buf` is popular enough, it may be feature-request worthy
Note: the `cerbos` org has been renamed to `planetscale`, this will require another PR to update the plugin
=> chore: renovate buf plugins

.github/workflows/container.yml
=> .github: Don't deduplicate container builds on merges

.github/workflows/build-test.yml, .github/workflows/codeql-analysis-go.yml, .github/workflows/codeql-analysis-js.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/go-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/proto-gen.yaml, .github/workflows/proto-pr.yaml, .github/workflows/proto-push.yaml, .github/workflows/release-dry-run.yml, .github/workflows/ui-publish-components.yml, .github/workflows/ui.yml
Follow up to #1303 
I did not intend to use the skip duplicate feature, I think we are only interested in path filtering for now.
https://github.com/fkirc/skip-duplicate-actions#skip_after_successful_duplicate
=> ci: disable skip_after_successful_duplicate

.github/workflows/build-test.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/go-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/proto-gen.yaml, .github/workflows/proto-pr.yaml, .github/workflows/proto-push.yaml, .github/workflows/release-dry-run.yml, .github/workflows/ui-publish-components.yml, .github/workflows/ui.yml, proto/buf.lock
This adds `.go-version` and `.node-version` files to path filters. I noticed checks were skipped in #1317
I also felt the need to sort them.
=> ci: ensure workflows run on Go/Node updates

.github/workflows/build-test.yml
A minor change which greatly improves readability of this workflow and some cleanup
It also uses the [`buildpack-deps`](https://hub.docker.com/_/buildpack-deps) image which already includes all the build tools and spares us from installing them ourselves
=> ci: use shell option to run commands in Docker

pkg/parcacol/arrow.go, pkg/query/columnquery.go
This happens when the timestamp for the query is too old or simply doesn't exist. Parca should return NotFound and not Unknown gRPC codes.
Sending this against the release-0.12 branch so it can be in the proper release.
=> pkg/query: Handle queries when no columns are found

pkg/profilestore/profilecolumnstore.go
If a profile buffer cannot be unzipped we should probably return `InvalidArgument` to the client and not say it's an internal error.
=> pkg/profilestore: Return grpc InvalidArgument if profile is not unzippable

.gitignore, README.md, go.mod, go.sum, parca.yaml, pkg/config/config.go, pkg/config/config_test.go, pkg/config/reloader_test.go, pkg/config/validation.go, pkg/debuginfo/metadata_test.go, pkg/debuginfo/store.go, pkg/debuginfo/store_test.go, pkg/metastore/badger.go, pkg/metastoretest/test.go, pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/parca/testdata/parca.yaml, pkg/parcacol/ingest.go, pkg/parcacol/schema.go, pkg/profilestore/profilecolumnstore.go, pkg/profilestore/profilestore_test.go, pkg/query/columnquery_test.go, pkg/query/query_test.go, pkg/symbolizer/symbolizer_test.go
This plugs all the persistence features of FrostDB into Parca.
=> *: Allow using persistence with WAL and object storage

go.mod, go.sum, pkg/parcacol/ingest.go, pkg/parcacol/ingest_test.go, pkg/parcacol/sample.go, pkg/parcacol/schema.go
With these changes we have 13.2x better space efficiency, meaning 13.2x
less in-memory and on-disk usage by columnar data managed by FrostDB.
The majority of the improvements came from choosing better encodings for each column but compression ultimately pushed it over the double-digit.
Running the numbers on a couple of blocks and I'm seeing ~2.91bytes per sample including label metadata and I don't even think we have reached what we can with multiple of these columns.
=> pkg/parcacol: Improve encodings and compression

ui/packages/shared/components/src/ProfileExplorer/index.tsx, ui/packages/shared/components/src/ProfileSelector/index.tsx
This fixes the blank screen that occurs when you do a compare in the Polar Signals cloud product. 
The culprit here was having multiple dispatch events next to each other as that causes React to rerender multiple times. Using the [batch](https://redux.js.org/faq/performance/#how-can-i-reduce-the-number-of-store-update-events) fn fixes that.
I tested this by creating a [prerelease](https://www.npmjs.com/package/@parca/components/v/0.14.3-alpha.2) and using it in my local dev environment of the cloud app, and a working preview can be seen [here](https://cloud-app-git-temp-fix-compare-mode.vercel-preview.polarsignals.com/)
=> area/ui: Use batch to prevent multiple rerenders

.github/workflows/ui-publish-components.yml
Possible solution to #1429.
The publish action fails while trying to push the tags and new publish commit to the repo as the main branch has push conditions, see: https://github.com/parca-dev/parca/runs/7536913694?check_suite_focus=true#step:8:26
As a first step trying, a PAT from admin user, so the push conditions are bypassed.
=> ci/ui: Using a separate token for UI package publish

pkg/parcacol/ingest.go
At present, when ingesting a profile that doesn't set a location id an error is logged. This stops that error from being logged.
This fix is simple, and the tests pass. I've just run the resultant binary in the situation where Parca was previously erroring every few seconds and things seem to be stable - perhaps there is some nuance I've missed elsewhere in the code, though?
Fixes #1264
=> fix: stop error on profile with no location id

pkg/parcacol/ingest.go, pkg/parcacol/ingest_test.go, pkg/parcacol/normalizer.go, pkg/parcacol/normalizer_test.go, pkg/query/flamegraph_flat_test.go, pkg/query/pprof_test.go, pkg/query/query_test.go, pkg/query/top_test.go
This is important for future work where we introduce the ability to
query samples by profile labels. In order to keep the same query
language we just force labels never to conflict so we always search by
process and profile labels at the same time.
=> pkg/parcacol: Ensure process labels don't overlap with profile labels

.github/workflows/build-test.yml
This should trim the `.0` from new minor releases. The download link is:
```
https://dl.google.com/go/go1.19.linux-arm64.tar.gz
```
Not:
```
https://dl.google.com/go/go1.19.0.linux-arm64.tar.gz
```
It would too simple otherwise
=> ci: fix Go arm64 download for new minor releases

.github/workflows/snap.yml
Enable `latest/edge` publishing on merges to `main` or `release-*` branches.
=> ci: tweak conditional for publishing snap to edge

Dockerfile, renovate.json
> Renovate failed to look up the following dependencies: `github.com/grpc-ecosystem/grpc-health-probe`.
I changed the datasource from Go modules to GitHub Releases, but forgot to update the dep name.
And the dev dockerfiles still use the Go module, so better group the updates
=> chore(renovate): fix grpc-health-probe

.github/workflows/build-test.yml, .github/workflows/codeql-analysis-go.yml, .github/workflows/codeql-analysis-js.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/go-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/proto-gen.yaml, .github/workflows/proto-pr.yaml, .github/workflows/proto-push.yaml, .github/workflows/release-dry-run.yml, .github/workflows/release.yml, .github/workflows/snap.yml, .github/workflows/ui-publish-components.yml, .github/workflows/ui.yml
This should unjam GitHub Actions when a lot of PRs/branches keep being updated
https://docs.github.com/en/actions/using-jobs/using-concurrency
It also adds a timeout to all jobs to ensure they are cancelled if stuck.
=> ci: cancel previous in-progress workflows

.github/workflows/snap.yml, README.md, go.mod, go.sum, pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/profilestore/profilestore_test.go, pkg/query/columnquery_test.go, pkg/query/query_test.go, pkg/symbolizer/symbolizer_test.go, snap/README.md, snap/hooks/configure, snap/parca-wrapper
This allows you to shutdown Parca, and on restarts query the historical data. Can see below where I shutdown Parca and started it much later
- updates version of frostdb to support persistence
- enables a graceful shutdown of the database on exit to write blocks to bucket storage
- refactors the persistence related flags to be less confusing:
1. To enable persistence you only need to provide the `--enable-persistence` flag
2. `--storage-persist` and `--storage-in-memory` has been removed.
3. To enable the WAL it is now `--storage-enable-wal`
4.  The `--metastore` flag now only accepts `badger` and the above persistence flags will determine if it's in-memory or not
=> Shutdown persistence

.github/workflows/codeql-analysis-go.yml, .github/workflows/codeql-analysis-js.yml
This fixes 2 issues:
* Go and JS workflows cancel each other because they have the same name
* fixes #1561 by ensuring the right versions of Go and Node are installed
=> ci: fix CodeQL analysis

pkg/parcacol/schema.go
Since FrostDB was updated the parquet-go library was too. It's new enough for the LZ4 fix to be included.
=> pkg/parcacol: Use LZ4 compression

scripts/local-tracing/otel-collector-config.yaml
They moved the insecure setting into the tls setting.
Remove a couple of things we don't need that were logging warnings.
=> scripts/local-tracings: Update otel-collector config

.github/workflows/container.yml
Fixes #1637 
I think by not specifying the fetch depth, the `checkout` action was calling `git fetch --no-tags`
=> ci: fix version parsing for container builds

.github/workflows/pre-commit.yml
I noticed `pre-commit` skips all hooks on the `main` branch. There, we want to check the last commit (assuming the merged PR has been squashed)
=> ci: fix pre-commit on main branch

ui/packages/app/web/src/components/ui/Navbar.tsx
Noticed a bug where the links in the Navbar were not working correctly in development mode (localhost:3000). The `window.PATH_PREFIX` returns a value of `{{.PathPrefix}}` in dev mode, even though it wasn't explicitly given a value. 
That meant the navbar links were pointing to invalid URLs. This is probably related to this [change](https://github.com/parca-dev/parca/pull/1679).
=> Don't use a path prefix when in development mode

pkg/parca/parca.go
Previously, the context that was used to call ListenAndServe was never cancelled.
cc @brancz
=> parca: cancel parcaserver application context when handling an interrupt

README.md, pkg/parca/parca.go
The latest version of FrostDB allows the usage of writing multiple n sized row groups during compaction and persistence. This adds a flag to enable that option in Parca.
=> Flag expose rowgroups

ui/package.json, ui/packages/shared/client/package.json, ui/packages/shared/components/package.json, ui/packages/shared/profile/package.json, ui/packages/shared/store/package.json, ui/yarn.lock
I added [tsc-watch](https://www.npmjs.com/package/tsc-watch) which allows us to run another command in addition to watching the TypeScript files. It has a `onSuccess` flag that lets you execute any command on every successful TypeScript compilation.
=> Use tsc-watch to watch TypeScript files and compile Tailwind files.

.github/workflows/ui-publish-components.yml
Enabling cancel-in-progress for the publish UI component job is creating a bug where the actual publish of the package to npm is failing. Lerna pushes the updated git tags to GitHub before publishing to npm, which is triggering another run of the workflow and in turn cancelling the in-progress publishing to npm.
And the newly triggered run wouldn't publish it either, as it already has the git tags that indicate that the npm publishing is update to date. 
Disabling `cancel-in-progress` for this workflow would fix it.
=> ci: Disabling cancel-in-progress for Publish UI components workflow

ui/packages/shared/profile/src/GraphTooltip/index.tsx, ui/packages/shared/profile/src/utils.ts
This PR truncates the build Id to just 16 characters.
**Before**
**After**
=> ui: Truncate build Id text

pkg/symbol/addr2line/symtab.go, pkg/symbol/addr2line/symtab_test.go, pkg/symbol/symbol.go
There were two issues:
- There was an off-by-one, which the first commit fixes + we were using the dynamic symbols, too, which I don't belive it's correct (but I will double check in a bit);
- Symbols were not demangled, which affects C++ and Rust
- Added some more unittests
- Cross checked against GNU's addr2line
- End-to-end visual checks below
**Before**
(note that symbols are not correct, and also, mangled)
**After**:
Signed-off-by: Francisco Javier Honduvilla Coto <javierhonduco@gmail.com>
=> Fix elf based symbolization

ui/packages/shared/profile/src/GraphTooltip/index.tsx, ui/packages/shared/profile/src/utils.ts
This is necessary as the maximum number that JS can represent is 2^53 [0].And show the addresses in the popover in hexadecimal.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
- [0] https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER
Signed-off-by: Francisco Javier Honduvilla Coto <javierhonduco@gmail.com>
=> ui: Use BigInt to represent 64 bit addresses

env-jsonnet.sh
This commit fixes make dev/setup failing due to an older version of golang.org/x/sys in github.com/google/go-jsonnet. The version was bumped in https://github.com/google/go-jsonnet/pull/633.
=> dev: update jsonnet version to 635d04f

go.mod, go.sum
This commit includes leveled compaction which should improve parca memory/cpu usage and query latency spikes.
=> deps: update frostdb to cc2d28d

.github/workflows/proto-gen.yaml
A leftover from before `fkirc/skip-duplicate-actions` and it prevents it from working
=> ci(proto-gen): remove on.pull_request.paths

deploy/lib/parca/parca.libsonnet
Follow up to #1403
Fixes:
```
level=error name=parca ts=2022-10-26T19:09:58.15050786Z caller=parca.go:138 msg="failed to read config" path=/var/parca/parca.yaml
level=error name=parca ts=2022-10-26T19:09:58.15054876Z caller=main.go:59 msg="Program exited with error" err="parsing YAML file /var/parca/parca.yaml: yaml: unmarshal errors:\n  line 1: field debug_info not found in type config.Config"
```
It was reported on Discord as well: https://discord.com/channels/877547706334199818/877547706334199821/1032955935255187498
=> fix(deploy): fix object_storage config

pkg/parcacol/querier.go
=> pkg/parcacol: Don't return empty label-values

pkg/query/flamegraph_table.go
We were resetting all function IDs to be `""`, which caused functions to override each other seemingly randomly.
=> pkg/query: Fix flamegraph function deduplication

pkg/query/flamegraph_table.go, pkg/query/flamegraph_table_test.go
Previously spans with locations that have no lines were incorrectly compared to locations with lines, which caused two locations that have the same lines to potentially not be sorted to be next to each other, causing merging not to work as expected.
=> Fix flamegraph span sorting

pkg/query/flamegraph_table.go, pkg/query/flamegraph_table_test.go
Previously there was a panic, when two locations were being compared that had no lines.
=> pkg/query: Fix comparing of two locations with only addresses

deploy/lib/parca/parca.libsonnet
#1989 was not enough.
Agent logs:
```
level=warn name=parca-agent ts=2022-11-10T22:29:57.054015758Z caller=manager.go:179 component=debuginfo buildid=4587364908de169dec62ffa538170118c1c3a078 path=/proc/6936/root/usr/lib/x86_64-linux-gnu/ld-2.31.so msg="failed to upload debug information" err="failed to upload debug information: close and receive: rpc error: code = Internal desc = failed to update metadata before uploading: failed to write metadata: mkdir /data: permission denied"
```
Server logs:
```
level=error name=parca ts=2022-11-10T22:30:00.573717776Z caller=metadata.go:211 component=debuginfo-metadata msg="failed to create metadata file" err="mkdir /data: permission denied"
level=error name=parca ts=2022-11-10T22:30:00.573778477Z caller=logger.go:38 protocol=grpc …
```
=> fix(deploy): fix local storage

pkg/debuginfo/store.go, pkg/symbol/symbol.go
While running Parca locally with parca-agent these logs made it seem like there were errors that needed to be fixed. While I think they are useful as debug logs, I don't think Parca should constantly log these messages.
=> Change log levels to not log recoverable errors as error level

pkg/config/config.go, pkg/scrape/scrape.go
While this may be necessary for some pprof HTTP endpoints, we have encountered others now that are already normalized, in which case normalizing them again is incorrect.
This is save to be added like this without changing existing behavior, as the value defaults to false which is the currently used value before this patch.
=> pkg/scrape: Allow profiles to be treated as already normalized

.github/workflows/pre-commit.yml, .pre-commit-config.yaml, proto/buf.lock
With #2162, fixes can be apply automatically, so hopefully this would fix Renovate PRs (and unless they need rebasing they should be able to merge automatically too) :grin:
I'll see if I can add a `buf-generate` hook upstream to avoid hacking another.
=> chore(pre-commit): add buf generate hook

pkg/profilestore/profilecolumnstore.go, pkg/profilestore/profilestore_test.go
Potentially it's possible to reduce allocs in `ProfileColumnStore.writeSeries` if it's possible to reuse a slice of labels (I followed the call stack and didn't find any concurrent access, but I might be missing something).
```
BenchmarkProfileColumnStoreWriteSeries-12  5725592  197.7 ns/op  120 B/op  5 allocs/op
BenchmarkProfileColumnStoreWriteSeries-12  4249389  259.8 ns/op  184 B/op  7 allocs/op
```
<details>
<summary>new</summary>
```
(pprof) list writeS
Total: 1.26GB
ROUTINE ======================== github.com/parca-dev/parca/pkg/profilestore.(*ProfileColumnStore).writeSeries
655.02MB   762.02MB (flat, cum) 59.16% of Total
.          .    105:}
.          .    106:
.          .    107:func (s *ProfileColumnStore) writeSeries(ctx context.Context, req *profilestorepb.WriteRawRequest) …
```
=> pkg/profilestore: Reduce allocs in writeSeries

pkg/symbol/addr2line/dwarf.go, pkg/symbol/symbol.go
Found this while taking a look at https://github.com/parca-dev/parca/issues/1757#issuecomment-1338061948
Signed-off-by: Francisco Javier Honduvilla Coto <javierhonduco@gmail.com>
=> symbolizer: Log addresses in hexadecimal

go.mod, go.sum, pkg/debuginfo/store.go, pkg/debuginfo/store_test.go
Previously we issued lots of repeated lookups in object storage. Since this data is immutable, once this result is positive, it will never change again, so we can cache the response forever.
How we got here: I noticed that our object storage bill was about ~50% class A operations (the other ~50% are egress network traffic). A quick Prometheus query revealed that 92% of all object storage requests are `iter` requests by the debuginfo API:
Then I queried some continuous profiling data to discover which stacks are spending the most CPU time (therefore most often called) that call the iter function (screenshot is from Polar Signals Cloud):
This shows clearly that the majority of times the `Exists` gRPC call calls the `iter` function, more specifically even the `find` function that I added …
=> pkg/debuginfo: Cache positive exists lookups

ui/packages/shared/components/src/Select/index.tsx, ui/packages/shared/profile/src/MatchersInput/index.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
=> fix query bar spacing bug

pkg/parcacol/schema.go
The stacktrace column was previously encoded as a RLE_DICTIONARY. This has been seen to cause memory bloat since the cardinality of stacktrace values is quite high.
=> parcacol: change stacktrace column to plain encoding

pkg/config/config.go, pkg/config/config_test.go, pkg/config/reloader_test.go, pkg/scrape/target.go
Use the scrape interval rather than the timeout to determine the profile duration on scraping. Since taking the profile will take strictly longer than the duration the timeout must be allowed to be larger as well. By default 3s are added to the interval based on real-world obvservations.
=> Use scrape interval correctly

ui/packages/app/web/vercel.json, ui/vercel.json
Since #1872, there are now two deployments and the root directories have changed
=> chore(ui): silence Vercel notifications

ui/packages/app/web/src/pages/targets.tsx
In scraper-only mode the agents gRPC service is not served, therefore returning `UNIMPLEMENTED`, which causes the UI not to be able to render the reply for the targets being scraped.
Additionally this patch also actually renders the errors that occur to allow for better troubleshooting when they do occur.
=> ui: Fix displaying targets error and handle scraper-only mode correctly

README.md, cmd/parca/main.go, pkg/config/validation.go, pkg/parca/logger.go, pkg/parca/parca.go, pkg/parca/parca_test.go
This is just a start. 
We probably want to start some of the Parca Agent structs here too (since they are already a bit more cleaned up).
Then Parca Agent could reuse the same structs to make for very consistent flags across projects.
=> pkg/parca: Create structs for flag categories

pkg/parcacol/schema.go
This has been shown to improve performance in benchmarks because more data can be filtered out at the scan layer before parquet decompression and conversion. Additionally, we will be able to take advantage of this ordering for more efficient execution using ordered aggregations.
=> parcacol: change schema sort order so that timestamp sorts before stacktrace

pkg/debuginfo/debuginfod.go
Turns out our debuginfod integration never worked ...
=> pkg/debuginfo: Fix instantiation of upstream debuginfod servers

pkg/parcacol/querier.go
This previously resulted in random strings showing up in the dropdown... Best case it was an empty string.
=> pkg/parcacol: Handle NULL strings in Values API call

ui/packages/shared/profile/src/IcicleGraph.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/TopTable/index.tsx, ui/yarn.lock
This will fix the current behaviour of the visualizations showing the `Profile has no samples` message for half a second before populating the visualisations with data. The code responsible for showing the message didn't take into account the value of the `loading` property. So I added that as a check before displaying that message.
I also removed the `disabled` property from buttons on ProfileView toolbar i.e. the share profile and download pprof buttons. They also flickered whenever selecting a new profile mostly because we had the disabled property set to the status of the data being loaded.
**demo.parca.dev**
This **PR**
TL:DR No more `Profile has no samples` message and less flickers in the profile view when selecting profiles.
One more thing: I still am not a fan on the very quick …
=> ui: Fix false positive Profile has no samples message in visualisations

Dockerfile.dev, Dockerfile.go.dev, ui/Dockerfile.dev
[mhart/alpine-node#deprecated](https://github.com/mhart/alpine-node#deprecated)
(The `# vim: ft=dockerfile` comment adds syntax highlighting in GitHub)
Related to #2540
=> chore(deps): use official nodejs image for development

go.mod, go.sum
This pulls in the following necessary fixes to sorting:
- https://github.com/segmentio/parquet-go/commit/1d85e81366814efe13170410a86be216a8c9b996
- https://github.com/polarsignals/frostdb/commit/a10ca984832919df73b347e6f4c2181800fd90dc
=> deps: update parquet and frostdb

pkg/parca/parca_test.go, pkg/parca/testdata/.gitignore, pkg/parca/testdata/pgotest.go
Add a test to ensure that the data exported by Parca can be used by Go's newly added profile-guided optimizations (PGO).
While testing this I realized that the functionality currently expects the samples count to be on index position 1 (understandable since that's where the runtime-generated profiles have it). But Parca takes the profiles apart and only returns a single sample type, therefore it currently panics, which is why this patch includes the small fix for the pprof profile. An issue has already been filed upstream: https://github.com/golang/go/issues/58292
=> pkg/parca: Add e2e test for Go PGO

cmd/parca/main.go, go.mod, go.sum
* Without CPU quota
```console
$ docker run --rm -v "${PWD}:${PWD}" -w "${PWD}" busybox bin/parca
[LOGO]
level=info name=parca ts=2023-02-15T19:45:41.246609299Z caller=main.go:57 msg="maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined"
level=info name=parca ts=2023-02-15T19:45:41.247233375Z caller=factory.go:52 msg="loading bucket configuration"
level=info name=parca ts=2023-02-15T19:45:41.251136091Z caller=badger.go:53 msg="Set nextTxnTs to 0"
level=info name=parca ts=2023-02-15T19:45:41.256082093Z caller=server.go:93 msg="starting server" addr=:7070
```
* With CPU quota
```console
$ docker run --rm --cpus 1 -v "${PWD}:${PWD}" -w "${PWD}" busybox bin/parca
[LOGO]
level=info name=parca ts=2023-02-15T19:48:05.507968398Z caller=main.go:57 msg="maxprocs: Updating GOMAXPROCS=1: determined …
```
=> perf: automatically set GOMAXPROCS to match Linux container CPU quota

pkg/debuginfo/metadata.go
must close the reader of bucket, or there would be many goroutine.
=> pkg/debuginfo: close bucket reader

buf.gen.yaml, gen/proto/go/google/api/http.pb.go, gen/proto/go/google/pprof/profile.pb.go, gen/proto/go/grpc/health/v1/health.pb.gw.go, gen/proto/go/parca/debuginfo/v1alpha1/debuginfo.pb.go, gen/proto/go/parca/debuginfo/v1alpha1/debuginfo.pb.gw.go, gen/proto/go/parca/metastore/v1alpha1/metastore.pb.gw.go, gen/proto/go/parca/profilestore/v1alpha1/profilestore.pb.gw.go, gen/proto/go/parca/query/v1alpha1/query.pb.go, gen/proto/go/parca/query/v1alpha1/query.pb.gw.go, gen/proto/go/parca/scrape/v1alpha1/scrape.pb.gw.go, gen/proto/go/parca/share/v1alpha1/share.pb.go, gen/proto/go/parca/share/v1alpha1/share.pb.gw.go, gen/proto/swagger/google/api/annotations.swagger.json, gen/proto/swagger/google/api/http.swagger.json, gen/proto/swagger/grpc/health/v1/health.swagger.json, gen/proto/swagger/parca/debuginfo/v1alpha1/debuginfo.swagger.json, gen/proto/swagger/parca/metastore/v1alpha1/metastore.swagger.json, gen/proto/swagger/parca/profilestore/v1alpha1/profilestore.swagger.json, gen/proto/swagger/parca/query/v1alpha1/query.swagger.json, gen/proto/swagger/parca/scrape/v1alpha1/scrape.swagger.json, gen/proto/swagger/parca/share/v1alpha1/share.swagger.json, go.mod, go.sum
Renovate bot is failing because the newer versions aren't available as the old custom plugins anymore.
=> Update `buf.gen.yaml` to use new buf plugins

ui/packages/shared/profile/src/Callgraph/index.tsx, ui/packages/shared/profile/src/ProfileView/ViewSelector.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/TopTable/index.tsx
We were not initializing a value for the `dashboard_items` param and this is causing pprof.me to crash.
This will ensure that other apps that uses the `ProfileView` component has a default value (`icicle`) to fall too
=> ui: Add a default visualization for the dashboard_items params

ui/packages/app/web/src/components/ReleaseNotesViewer/index.tsx, ui/packages/shared/components/src/Button/index.tsx
Strangely, the `Press Shift to copy` is working fine in this branch, will wait for the preview build.
=> ui: User preferences icon and release notes viewer bugfix

ui/packages/shared/profile/src/GraphTooltip/index.tsx, ui/packages/shared/profile/src/ProfileExplorer/ProfileExplorerSingle.tsx, ui/packages/shared/profile/src/ProfileExplorer/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/IcicleGraphNodes.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraph/index.tsx, ui/packages/shared/store/package.json, ui/packages/shared/store/src/slices/colorsSlice.ts
Moved the `hoveringNode` state from the `IcicleGraph` component to redux store to prevent the unwanted renders while hovering around the flamegraph.
=> ui: Flamegraph tooltip perf improvement

go.mod, pkg/config/config.go, pkg/config/secret.go, pkg/debuginfo/metadata_test.go, pkg/parca/parca.go, pkg/signedupload/client.go, pkg/signedupload/gcs.go, pkg/symbolizer/symbolizer_test.go
Renovate crashes on this update without a meaningful error and I cannot reproduce it locally, so doing it manually.
Notable breaking changes:
* go-yaml/yaml@085f3822ccabf97875c60131b52575a980b634a8
* go-yaml/yaml@309c9d15755818936fcb0f5c171692693a47efe2
=> build(deps): update module gopkg.in/yaml.v2 to v3

pkg/debuginfo/debuginfod.go, pkg/debuginfo/debuginfod_test.go, pkg/debuginfo/store.go, pkg/debuginfo/store_test.go
This patch does two main things aside from a small cleanup and simplification:
* Fix caching: Previously while we wrote debuginfo to the object storage cache, we never tried to read if from there in the future.
* Follow redirects if an upstream debuginfod server returns a HTTP 3xx response.
Fixes #2240
=> pkg/debuginfod: Fix caching and follow redirects of debuginfod servers

ui/packages/app/web/src/components/ui/Navbar.tsx
Seems like we missed updating the styles for small screens.
=> Update outdated navbar styles for phones

pkg/query/columnquery.go, pkg/query/flamegraph_flat_test.go, pkg/query/flamegraph_table.go, pkg/query/flamegraph_table_test.go
The render flamegraph function can spend a lot of time allocating and gc'ing buffers. This adds a sync.pool for the buffers for rendering.
```
thor@thors-MacBook-Pro query % benchstat before.txt after.txt
name                                     old time/op    new time/op    delta
_GenerateFlamegraphTable_FromProfile-10     760µs ± 5%     696µs ± 5%  -8.35%  (p=0.000 n=10+10)
name                                     old alloc/op   new alloc/op   delta
_GenerateFlamegraphTable_FromProfile-10    1.23MB ± 0%    1.15MB ± 0%  -6.68%  (p=0.000 n=10+9)
name                                     old allocs/op  new allocs/op  delta
_GenerateFlamegraphTable_FromProfile-10     11.7k ± 0%     11.6k ± 0%  -0.64%  (p=0.000 n=10+10)
```
It produces moderate savings
=> Optimize render flamegraph

pkg/debuginfo/debuginfod.go, pkg/debuginfo/debuginfod_test.go, pkg/parca/parca.go
Fixes https://github.com/parca-dev/parca/issues/2914
=> pkg/debuginfo: Set debuginfod user-agent

ui/packages/app/web/src/pages/targets.tsx, ui/packages/shared/components/src/Pill/index.tsx
Been using the dark mode a bit more recently (macOS auto switches) and these pills really caught my eye :smile:
=> ui: Improve dark styling for targets page and Pill component

ui/packages/shared/components/src/Select/index.tsx
This PR introduces a fix to the dropdown options not being fixed to the dropdown button. When Parca was used within a different application (such as Polar Signals Cloud) the dropdown options position changed on page scroll
=> fix dropdown component

ui/packages/app/web/src/components/ReleaseNotesViewer/index.tsx
The `Full Changelog` button is pointing to https://github.com/parca-dev/parca/releases/tag/0.17.0 instead of https://github.com/parca-dev/parca/releases/tag/v0.17.0
=> Fix link to release page

pkg/parcacol/ingest_test.go, pkg/parcacol/normalizer.go, pkg/parcacol/normalizer_test.go
I was looking where `NormalizeWriteRawRequest` allocates and found a low hanging fruit in `sampleKey` function.
```
BenchmarkSampleKey-12    	 4405494	       279.3 ns/op	     437 B/op	       3 allocs/op
BenchmarkSampleKey-12    	 1849962	       711.8 ns/op	     712 B/op	      10 allocs/op
```
That change reduced allocations in `NormalizeWriteRawRequest` a bit (14K less allocations per operation).
```
$ go test -run=^$ -bench ^BenchmarkNormalizeWriteRawRequest$ -benchmem ./pkg/parcacol -count=50 . | tee bench-new.txt
$ benchstat bench-old.txt bench-new.txt
name                         old time/op    new time/op    delta
NormalizeWriteRawRequest-12    43.9ms ± 7%    43.0ms ± 5%  -2.07%  (p=0.001 n=47+45)
name                         old alloc/op   new alloc/op   delta …
```
=> pkg/parcacol: Reduce allocs in sampleKey

pkg/metastore/badger.go, pkg/metastore/kv.go, pkg/metastore/kv_test.go
Reduced allocations in `MakeLocationID`.
```
$ go test -run=^$ -bench ^BenchmarkMakeLocationID$ -benchmem ./pkg/metastore -count=1
...
BenchmarkMakeLocationID-12    	 3224959	       370.4 ns/op	      96 B/op	       1 allocs/op
BenchmarkMakeLocationID-12    	 1859330	       647.9 ns/op	     560 B/op	      10 allocs/op
```
This helped to shave 17K allocations per operation in `NormalizeWriteRawRequest`.
```
$ benchstat bench-old.txt bench-new.txt
name                         old time/op    new time/op    delta
NormalizeWriteRawRequest-12    43.9ms ± 7%    43.1ms ± 5%  -1.89%  (p=0.001 n=47+46)
name                         old alloc/op   new alloc/op   delta
NormalizeWriteRawRequest-12    53.5MB ± 1%    52.7MB ± 1%  -1.62%  (p=0.000 n=50+50)
name                         old allocs/op  new …
```
=> pkg/metastore: Reduce allocs in MakeLocationID

pkg/parcacol/ingest_test.go
Seems like something was incorrectly merged or rebased or whatever after #2955...
This should fix the CI currently failing on `main`.
cc @marselester @kakkoyun
=> pkg/parcacol: Fix NewNormalizer call in test

go.mod, go.sum, pkg/parca/parca.go, pkg/server/server.go
Had some time on a boring train ride and thus worked on this 🚄 
It works like a charm! 🥳 
Here's the upstream PR https://github.com/grpc-ecosystem/go-grpc-middleware/pull/584 that we depend on to eventually remove the replace directive again.
=> pkg: Use native histograms for gRPC request/responses

cmd/parca/main.go, go.mod, go.sum, pkg/server/grpc_codec.go
In #3019, I overlooked the health and reflection GPRC services which do not have optimized `vtprotobuf` marshalling code. As a result, the demo pod is stuck in a crash loop with its health probe failing:
```
Events:
Type     Reason     Age                  From     Message
----     ------     ----                 ----     -------
Warning  Unhealthy  10m (x165 over 85m)  kubelet  (combined from similar events): Readiness probe failed: parsed options:
> addr=:7070 conn_timeout=1s rpc_timeout=1s
> tls=false
> alts=false
> spiffe=false
establishing connection
connection established (took 1.948716ms)
error: health rpc failed: rpc error: code = Internal desc = grpc: error unmarshalling request: failed to unmarshal, message is *grpc_health_v1.HealthCheckRequest (missing vtprotobuf helpers) …
```
=> fix: conditionally select GRPC codec

ui/packages/shared/components/src/hooks/useURLState.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx
This fixes the bug in [#1991](https://github.com/polarsignals/polarsignals/issues/1991#event-9340441410). 
**Steps to reproduce bug**
- Pull up any icicle graph
- Apply a function filter
- ~~Expand something in the icicle graph~~
- ~~Click on root node~~
- Remove function filter
- From now on anything you click on in the icicle graph has this bug. 
A couple of things to note:
**TL:DR: Removed the `navigateTo` function as a dependency in the useEffect hook in the in the `useURLState` hook.**
This bug doesn't seem to happen in Parca but only on PSC. After some investigating, I discovered this is because this [useEffect](https://github.com/parca-dev/parca/blob/main/ui/packages/shared/profile/src/ProfileView/index.tsx#L136) keeps firing after a function filter has been removed i.e. setting …
=> ui: Remove useEffect fn responsible for resetting current icicle path

pkg/config/reloader.go, pkg/config/reloader_test.go
This properly handle reloading the configuration from a Kubernetes ConfigMap which uses a symlink, a case I had initially overlooked.
In this case, the reload is triggered by the deletion of the old version of the config, not the symlink deletion/re-creation as fsnotify follows them when creating the watcher.
=> fix(config): fix reloading config from Kubernetes ConfigMap

pkg/scrape/scrape.go, pkg/scrape/target.go
This applies allocation optimizations related to scraping targets.
See upstream PR prometheus/prometheus#12048 and prometheus/prometheus#12084 (and prometheus/prometheus#12173)
=> perf(scrape): apply optimizations from upstream prometheus

ui/packages/shared/components/package.json, ui/packages/shared/components/src/TextWithTooltip/index.tsx, ui/yarn.lock
Upgraded react-tooltip to version 5.13.0 in order to remove the CSS import that was causing issues. See here for more info: https://github.com/ReactTooltip/react-tooltip#usage
=> upgrade react-tooltip package

pkg/debuginfo/store.go
Since parca-agent started to create spans from the client side, `SpanFromContext` has started to create problems. 
Even though operations successfully finish since OTel SDK propagates the context from/to the client-side agent receives a timed-out/closed context.
This was causing errors on the agent side. 
The PR ensures a new context is created, and the child context is closed when the operation is finished without touching the parent(incoming) context.
Fixes https://github.com/parca-dev/parca-agent/issues/1741
=> debuginfo/store: Use tracer.Start instead of SpanFromContext

ui/packages/app/web/src/components/ui/ThemeToggle.tsx, ui/packages/shared/components/src/Dropdown/index.tsx, ui/packages/shared/store/src/slices/uiSlice.ts
After demoing this during Parca Office hours, we came to the consensus that the system settings theme mode should be chosen automatically, as opposed to the previous method where the user had to first select system settings.
=> ui: Automatically use system settings for Parca's theme

.github/workflows/chromatic.yml, .github/workflows/ui-publish-components.yml, Makefile, ui/package.json
This PR removes the usage of lerna bootsrap and simply replaces with yarn install as documented [here](https://lerna.js.org/docs/legacy-package-management).
=> Remove usage of lerna bootstrap

pkg/server/server.go
After much testing, I found out the following:
HTTP1.1 works: :heavy_check_mark:
```shell
$ curl --http1.1 127.0.0.1:7070/api/grpc.health.v1.Health/Check \
-H 'Content-Type: application/grpc-web-text' \
-H 'Accept: application/grpc-web-text' \
-d 'AAAAAAA='
AAAAAAIIAQ==gAAAABBncnBjLXN0YXR1czogMA0K
```
H2C (HTTP2 upgraded from HTTP1.1) works: :heavy_check_mark:
```shell
$ curl --http2 127.0.0.1:7070/api/grpc.health.v1.Health/Check \
-H 'Content-Type: application/grpc-web-text' \
-H 'Accept: application/grpc-web-text' \
-d 'AAAAAAA='
AAAAAAIIAQ==gAAAABBncnBjLXN0YXR1czogMA0K
```
HTTP2 (without upgrade from HTTP1.1) does not work: :x:
```shell
$ curl --http2-prior-knowledge 127.0.0.1:7070/api/grpc.health.v1.Health/Check \
-H 'Content-Type: application/grpc-web-text' \
-H 'Accept: …
```
=> fix(server): handle gRPC-Web requests over HTTP2

ui/packages/shared/utilities/src/bigint.spec.ts, ui/packages/shared/utilities/src/bigint.ts
Fix for `RangeError: The number 1562.0240478515625 cannot be converted to a BigInt because it is not an integer` error that happens when the font size of the page is increased/decreased in the browser when the flame graph is already loaded.
=> ui: Flamegraph crash fix

ui/packages/shared/utilities/src/bigint.spec.ts, ui/packages/shared/utilities/src/bigint.ts
Root cause: This happens when the `linearScales`'s domain range is so high compared to the device width range, making the `rate` a `0`, so no nodes in the flame graph are rendered. 
Fixed it by increasing the multiple to the same number of digits as `Number.MAX_SAFE_INTEGER`, so that the `rate` is not rounded off to `0`.
=> ui: Fixes the bug where flamegraph goes blank for some instrumented profiles 

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Turns out we already inlined almost correctly. pprof just stores the lines in reverse order, just like the locations too. Flipping these around did the trick.
Comparing the arrow and table flame graphs the inlining seems fine now.
=> pkg/query: TestGenerateFlamegraphArrowWithInlined

README.md, pkg/parca/parca.go
Parca would previously not snapshot frostdb data. This commit enables snapshotting by default each 1/4 of maximum active memroy and exposes a flag to tune this snapshot trigger size further. This allows recovery to be much faster than replaying all writes from the WAL.
Users that would previously see the parca server take a long time to start or have the impression that the server was hung indefinitely during startup will benefit from this commit.
Fixes #3430
=> parca: add --storage-snapshot-trigger-size

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleGraphNodes.tsx
To support adding rows with just addresses, we'd have had to copy a lot of code. This was the perfect opportunity to finally introduce a better abstract - the `flamegraphBuilder`. 
There are some other pieces we may consider moving into this struct/builder in the future. I can also see having something like a `flamegraphBuilder.NewRecord()` to wrap some of the internals even more. Overall, these are minor improvements though. 
The UI needed some small tweaks to properly support function names being `null`.
=> pkg/query: Support unsymbolized profiles with arrow fg

pkg/query/flamegraph_arrow.go
We were counting inlined functions additionally.
=> pkg/query: Correctly sum up total cumulative value

pkg/query/flamegraph_arrow.go
Arrow casts this internal but apparently copies the string to bytes. This codes uses the stringToBytes helper which does not copy using the `unsafe.StringData` API.
```
name      old time/op    new time/op    delta
Query-24     440µs ± 6%     398µs ± 8%  -9.59%  (p=0.032 n=5+5)
name      old alloc/op   new alloc/op   delta
Query-24     470kB ± 0%     460kB ± 0%  -2.12%  (p=0.008 n=5+5)
name      old allocs/op  new allocs/op  delta
Query-24     2.79k ± 0%     2.53k ± 0%  -9.25%  (p=0.008 n=5+5)
```
=> pkg/query/flamegraph_arrow: Cast strings to bytes

pkg/query/flamegraph_arrow.go
This reverts commit aa604de41d8556b046b806609e186bf2d966e1ea.
Sadly Arrow JS doesn't support lz4 compression (yet):
https://github.com/apache/arrow/issues/24833
https://github.com/apache/arrow/pull/13076
=> Revert "compress the flamegraph record with lz4 (#3459)"

.github/workflows/go-lint.yml, Makefile
#3472 caused unexpected CI failures: 
- https://github.com/parca-dev/parca/actions/runs/5613158920/job/15208568702?pr=3487
- https://github.com/parca-dev/parca/actions/runs/5613158924/job/15208563093?pr=3487
This should fix the issues 🤞
=> ci: Only run govulncheck on go/lint

parca.yaml, pkg/config/config.go, pkg/scrape/scrape.go, pkg/scrape/target.go
If a config specifies a `keep_sample_types` allow-list in then scrape config then we'll parse the scraped pprof profile and keep only those samples within a profile that match one of the listed sample types. This is especially useful for cases where users only want to ingest heap profiling data, for which there is no way in the pprof endpoints in Go to ignore other data at collection time.
=> pkg/config: Allow configuring to keep only certain sample types

pkg/query/flamegraph_arrow.go
The generic version is a lot more expensive as it grows the slice one by one, instead of pre-allocating the result size.
=> pkg/query: Use non-generic method to clone children list

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleGraphNodes.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/utils.ts
On the backend, we check every sample for its pprof labels.
If it has pprof labels we either inject a artifical node into the stack containing the pprof labels as JSON for the function name, or we merge the stack into the already existing same pprof label node. 
In the frontend, instead of showing `{"thread_name":"foo"}` we're going to parse the JSON and display it as `thread_name="foo"` in a Prometheus fashion. Given that each injected pprof label node is unique the drilling down into the icicle graph by function name now works flawlessly again. :+1:
=> flamegraph_arrow: Inject artifical label node

pkg/query/flamegraph_arrow.go, pkg/query/json.go
Additionally, there was the assumption that the MarshalStringMap is sorted which broke the key access to the rootsRow map. Therefore, for the specific case a MarshalStringMapSorted was added (again).
=> pkg/query/flamegraph_arrow: Cast bytes to string when accessing maps keys

.github/workflows/build-test.yml, .github/workflows/chromatic.yml, .github/workflows/codeql-analysis-go.yml, .github/workflows/codeql-analysis-js.yml, .github/workflows/container.yml, .github/workflows/docs.yml, .github/workflows/go-lint.yml, .github/workflows/jsonnet.yml, .github/workflows/pre-commit.yml, .github/workflows/proto-gen.yaml, .github/workflows/proto-pr.yaml, .github/workflows/proto-push.yaml, .github/workflows/release-dry-run.yml, .github/workflows/snap.yml, .github/workflows/ui.yml, .golangci.yml
Seems like these are needed so the checks are actually run with the merge_groups.
=> Add main merge_group to workflows

snap/hooks/configure, snap/parca-wrapper
Add a config option to the Parca snap to simplify the onboarding to Parca Cloud.
This change introduces a new snap config option named remote-store-bearer-token, and sets the default store address to grpc.polarsignals.com:443.
When a token is set, any other config about storage persistence or memory is ignored, and Parca's mode is set to `scraper-only`.
=> feat(snap): add config options to send profiles to a remote store

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
So far, the `AppendNull` has been used for the first time a row showed up. Even overwriting (adding new diff values) to the row resulted in the value being returned as null, although the underlying value was there.
Notice the blue functions in the first two rows:
Notice that the functions in the first two rows now have the proper color:
=> pkg/query/flamegraph_arrow: Expose diff values, dont set to null

.github/workflows/snap.yml
Latest PR that merged broke the snap tests - this should fix that.
I didn't catch this because the skip-check meant the CI tests didn't run on the original PR. I'll take a look at that in a while :)
=> ci: fix snap test - s/port/http-address/g

pkg/debuginfo/store.go
This allows us to rather base the decision of what file tyte is being used by looking at the magic number rather than limiting ourselves just to tarballs.
=> pkg/debuginfo: Save sources upload without extension

go.mod, go.sum, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Previously the height was estimated, but didn't take inlined functions and injected label nodes into account.
=> pkg/query/flamegraph_arrow: Properly calculate height

go.mod, go.sum, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/utils.ts
Previously we looked at each individual string to be inserted into the resulting flamegraph, which was very inefficient since strings occur many times over. That causes dictionary building to be inefficient, but also comparisons are done on strings rather than integers.
Changing this to use dictionary unification and transposing yielded a very good performance improvement:
```
name                old time/op  new time/op  delta
ArrowFlamegraph-10  5.95ms ± 0%  3.38ms ± 0%  -43.28%  (p=0.008 n=5+5)
```
=> pkg/query: Improve flamegraph performance through dictionary unification

pkg/symbol/addr2line/dwarf_test.go, pkg/symbol/elfutils/debuginfofile.go
Adds the `StartLine` to the profile Function during symbolization. This is needed to support pgo https://go.dev/doc/pgo#alternative-sources
> [Function.start_line](https://github.com/google/pprof/blob/76d1ae5aea2b3f738f2058d17533b747a1a5cd01/proto/profile.proto#L215) must be set. This is the line number of the start of the function. i.e., the line containing the func keyword. The Go compiler uses this field to compute line offsets of samples (Location.Line.line - Function.start_line). Note that many existing pprof converters omit this field.
Tested using pprof that was collected by parca-agent & downloaded from pacra UI.
Before:
```
$ go build  -gcflags="all=-N -l" -o bin/ -pgo ~/Downloads/profile_before.pb ./my/test
compile: /home/albertlockett/Downloads/profile(1).pb: PGO error: profile …
```
=> add startline to function when symbolizing elf

go.mod, go.sum, pkg/profile/reader.go, pkg/query/flamegraph_arrow.go
With these changes we can render ~800k unique stacks within ~2s. There's still more that can be done, but I felt like this would be a good check in.
All these changes have already been verified to be working as expected by running them on Polar Signals Cloud for some time.
=> Improve flamegraph rendering performance

pkg/parca/parca_test.go, pkg/parcacol/arrow_test.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, pkg/query/flamegraph_table_test.go, pkg/query/query_test.go, pkg/query/table_test.go
Uses a checked allocator throughout unit tests. 
This exposed some allocation leaks that were fixed as well.
=> Use checked allocator

pkg/query/flamegraph_arrow.go
I haven't been able to write a test yet that ensures we don't break this again, but I can verify with customer data that this works as intended now.
=> pkg/query: Fix how inlined functions are determined to be root

ui/packages/shared/profile/src/Table/index.tsx
Turns out the function names are actually empty strings here and not null.
Checking for null probably doesn't hurt, so I left that in too.
=> ui/packages/profile/Table: Check functionname for empty string

Makefile, pkg/parcacol/querier.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go
Fixes the double free in the `TestColumnQueryAPIQueryDiff`
Fixes all the double frees in the query tests. Turns on the `assert` tag for all go tests
=> Fix double free

ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/Table/index.tsx
With this fix, if the user hits "Clear selection" in the table and something has been previously entered in the "filter by function" input, the highlighting will revert to the filtered result instead of improperly clearing all highlighting (as had been the case before the fix).
=> Fix Clear Selection button in table

go.mod, go.sum, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Fork of https://github.com/parca-dev/parca/pull/3722 with memory leak fixes
This adds trimming based on breadth-first-search using dictionary compaction. 
It passes the tests locally now. :relieved: :tada: 
Some TODOs are left either to fix within this PR or as follow-ups.
=>  pkg/query/flamegraph_arrow: Trim using breadth-first-search #3722 

ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx
Detecting the width form within the component is creating a flaky situation where the `ref.current` might not be populated based on whether the child component has rendered or not, that was making the width to `undefined` sometimes causing the flame graph not visible. 
So, this fix passed the width from the parent component so that we can be well sure that the ref is already populated.
=> ui: Flamegraph - passing width from the parent instead of detecting from within

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileView/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx
Instead of building the table from the response object right away, pass down the wrapper with additional information, such as trimming value.
Only in the final step, right before building the icicle graph, parse the record bytes into an actual arrow table.
`Trimmed 7 (0.267%) too small values.` shows up with both flame graph report types now.
=> ui/shared/profile: Pass down arrow response object

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, pkg/query/table_test.go
This improves the performance of building flamegraph API responses
dramatically. The major change is that instead of keeping children as
slices and iterating over them to find which child to step into when
building the graph, we build a key based on the fields we're aggregating
by and use that to check if the children map already contains it.
```
name                old time/op  new time/op  delta
ArrowFlamegraph-10  5.04ms ± 2%  1.58ms ± 2%  -68.66%  (p=0.008 n=5+5)
```
The second commit adds some helpers to ensure we sort the result, so we get a deterministic result.
=> pkg/query: Use maps instead of slices for children for O(1) access

renovate.json
Widen start of the scheduling window as well: lots of dependencies, so the backlog grows quickly if little time is given to process it
=> chore(renovate): allow scheduling on weekends

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
This is going to return an empty (except for the root row) arrow record with all columns and one root row.
The frontend can then handle the case the record has 0 or 1 row.
This was approach was in favor over returning an no-data-error as it signals that the request overall was correctly processed.
=> pkg/query/flamegraph_arrow: Return empty record if no samples

parca.yaml
Scraping every 10s should be totally fine for most use cases.
Also, naming the job parca seems much more descriptive than default.
=> Disable Parca scraping by default

pkg/parcacol/arrow.go, pkg/profile/profile.go, pkg/profile/reader.go, pkg/profile/writer.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/sources.go, pkg/query/table.go
Anything that needs to be built adds latency to the query path, and this removes a number of dynamic dispatch calls and prevents 2 validity bitmaps from being built.
=> *: Remove unnecessary arrow structs

pkg/query/flamegraph_arrow_test.go
This is going to walk the flamegraph depth first and sort each row's children based on pprof labels and then function names.
=> pkg/query/flamegraph_arrow: Add testing flamegraphComparer

ui/packages/shared/components/src/UserPreferences/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx
We're confident in the arrow flame graph implementation now.
The same is true for trimming. 
Make the arrow flame graph the default. Always enabled trimming. 
Remove the obsolete user preferences.
=> ui: Make arrow flamegraph the default

pkg/profile/reader.go, pkg/query/columnquery.go, pkg/query/flamegraph_arrow.go, pkg/query/sources.go, pkg/query/table.go
GetValueIndex performs some work to access the underlying array on every call. Since building the flamegraph accesses the underlying array a lot it makes sense to perform that once, and then access the array.
It turns out that ends up being a lot of work:
```
name                old time/op  new time/op  delta
ArrowFlamegraph-10  1.55ms ± 1%  1.34ms ± 1%  -13.65%  (p=0.000 n=45+10)
```
=> pkg/query: Don't use GetValueIndex, use raw underlying array

.pre-commit-config.yaml, go.mod, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Benchmarks have shown no negative CPU impact due to the typecasting. Instead, memory allocation was reduced, as expected.
If the record crosses 16MiB we attach some stats about the record to the tracing span.
=> pkg/query: Use optimal index uint type for dictionaries

pkg/profile/reader.go, pkg/profile/writer.go, pkg/query/columnquery.go, pkg/query/flamegraph_arrow.go
Surprising how much more perf improvements we keep finding:
```
name                old time/op  new time/op  delta
ArrowFlamegraph-10  1.35ms ± 1%  1.15ms ± 1%  -14.25%  (p=0.000 n=10+10)
```
=> Various small arrow flamegraph perf improvements

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Given those are unused in the UI and make up almost 20% of bytes in the arrow record, it's time to finally remove them.
```
name                old time/op    new time/op    delta
ArrowFlamegraph-24    1.88ms ± 6%    1.56ms ±15%  -16.62%  (p=0.000 n=10+10)
name                old alloc/op   new alloc/op   delta
ArrowFlamegraph-24    2.49MB ± 0%    2.00MB ± 1%  -19.84%  (p=0.000 n=10+10)
name                old allocs/op  new allocs/op  delta
ArrowFlamegraph-24     7.31k ± 0%     7.11k ± 1%   -2.72%  (p=0.000 n=10+10)
```
=> pkg/query/flamegraph_arrow: Remove mapping start,limit,offset

pkg/metastore/kv.go
This panicked in some rare case.
=> pkg/metastore: Guard against function being nil

pkg/query/flamegraph_arrow.go, pkg/query/table.go, pkg/query/table_test.go, ui/packages/shared/profile/src/Table/index.tsx
We don't use these mapping columns anywhere in the UI. 
Similar to the flame graph this won't most likely be ever used.
=> pkg/query: Remove unused mapping columns from arrow table

ui/packages/shared/profile/src/ProfileSelector/CompareButton.tsx
This seems to be an oversight and the Compare button should really be neutral/secondary next to the primary Search button.
=> ui/profile/CompareButton: Use variant neutral

ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/components/ProfileShareButton/index.tsx
This fixes a bug where clicking on the "Copy Link" button in the profile sharing modal refreshes the page and navigates to the homepage (`/`). The use of the `form` tag seemed to be the issue here.
This also fixes a bug I noticed where hovering on any part of the icicle graph causes the app to crash instantly, with the error seen in the screenshot below. Looks like the check `mappingBuildID === null` wasn't enough, changing it to `!mappingBuildID` worked.
=> Fix sharing profile bug

pkg/query/columnquery.go
Unfortunately, when a dictionary has only a single (empty) entry, when that entry is read, the array returns `[]byte(nil)`.
=> pkg/query: Transfer empty values from empty dictionaries correctly

README.md, go.mod, go.sum, pkg/parca/parca.go, pkg/parcacol/ingest.go, pkg/parcacol/ingest_test.go
Arrow ingestion is now the only supported type of profile ingestion
=> Remove ExperimentalArrow flag

pkg/scrape/scrape.go
A storage expects that when executable infos are set, that they are equal to the amount of mappings in a sample.
=> pkg/scrape: Fix scraping without executable info

pkg/config/config.go, pkg/config/config_test.go, pkg/config/validation.go
This commit fixes the problem when jobs with the same names are [compacted to a single target](https://github.com/parca-dev/parca/blob/912596987067593ddb69f7fe12dc6b43eae9d8d7/pkg/scrape/manager.go#L110-L114), leading to unexpected behavior: a user will only see the last target with this job name.
It is a breaking change for users who have duplicates in their configs, but for new users, it will be more transparent.
=> config: Validate duplicate job names

proto/parca/debuginfo/v1alpha1/debuginfo.proto, proto/parca/metastore/v1alpha1/metastore.proto, proto/parca/profilestore/v1alpha1/profilestore.proto, proto/parca/query/v1alpha1/query.proto, proto/parca/scrape/v1alpha1/scrape.proto, proto/parca/share/v1alpha1/share.proto, proto/parca/telemetry/v1alpha1/telemetry.proto
Note: This doesn't produce any changes to the generated code, so the `buf-breaking` lint error can be ignored.
=> protobuf: Declaring go_package as a potential fix for downstream usage

snap/parca-wrapper
This adds additional options to be able to configure the `--path-prefix` and `--debuginfod-upstream-servers` arguments of the `parca` binary.
=> Add additional snap configuration options

snap/parca-wrapper
This corrects #4069 where I missed to add some late changes to correct the option to specify custom debuginfod servers.
=> fix(snap): correct debuginfod upstream servers option

pkg/scrape/target.go
Hello!
I've been bitten by this panic:
```
goroutine 276 [running]:
github.com/parca-dev/parca/pkg/scrape.LabelsByProfiles(0x4007237d58?, 0x39bdb00?)
github.com/parca-dev/parca/pkg/scrape/target.go:233 +0x120
github.com/parca-dev/parca/pkg/scrape.targetsFromGroup(0x400f5b6ea0, 0x400187c420, {0x0?, 0x46e?, 0x500?}, 0x4007237f10)
github.com/parca-dev/parca/pkg/scrape/target.go:370 +0x158
github.com/parca-dev/parca/pkg/scrape.(*scrapePool).Sync(0x400ffa0b40, {0x40078ba000, 0x46e, 0x40073a8e40?})
github.com/parca-dev/parca/pkg/scrape/scrape.go:218 +0x228
github.com/parca-dev/parca/pkg/scrape.(*Manager).reload.func1(0x0?, {0x40078ba000?, 0x4001880a90?, 0x4000fa8160?})
github.com/parca-dev/parca/pkg/scrape/manager.go:217 +0x28
created by github.com/parca-dev/parca/pkg/scrape.(*Manager).reload …
```
=> Handle possible nil in profiling config

ui/packages/shared/profile/src/ProfileSelector/index.tsx
Fixes a bug where the ProfileSelector component is trying to set the query expression before it has been successfully fetched from the URL. Adding an early return to the useEffect, and adding `queryExpression` to the dependency array fixes this.
=> Fix bug when loading Metrics graph

ui/packages/shared/components/src/DateTimeRangePicker/AbsoluteDatePicker/index.tsx
When zooming in the metrics graph using the drag and drop interaction, everything is updated (graph and icicle) but not the time selector in UI.
After some investigation, I discovered the selector is updated after the first zoom but fails to do so for any other subsequent zooms. 
This was due to the `from` and `to` local states in the `ui/packages/shared/components/src/DateTimeRangePicker/AbsoluteDatePicker/index.tsx` file not being updated when the `range` prop changes. Adding a `useEffect` with a dependency of `range` to update the `from` and `to` seems to fix the bug.
_To recreate the original bug, zoom in on the metrics graph using the drag and drop interaction, then do another zoom and you'll notice the date and time isn't being updated._
=> area/ui: Fix datetime picker bug when zooming on graph using mouse drag and drop

pkg/parcacol/ingest_test.go
Ingester no longer inserts parquet data to `frostdb` the tests were passing by accident (assertions were in the wrong block that was never executed).
I needed these tests to be correct and passing because a lot of work has been done on `frostdb` to facilitate automatic record generation. To upgrade to these new improvements.
- Both implementation must generate the same output `arrow.Record`
I included generated arrows in `testdata` directory  for the reason above.
=> Fix Ingester tests

.github/workflows/docs.yml, .github/workflows/go-lint.yml, .github/workflows/proto-gen.yaml, pkg/parca/parca.go, pkg/server/server.go, proto/buf.lock, ui/packages/app/web/build/keep.go
This will make it easier to consume the server outside of parca itself.
=> pkg: Move the uiFS out of the server package

Dockerfile
If `/data` doesn't exist, `nobody` cannot create it so it fails all the time.
=> Fix Dockerfile for parca server

ui/packages/shared/components/src/DateTimeRangePicker/RelativeDatePicker/index.tsx, ui/packages/shared/components/src/DateTimeRangePicker/utils.ts, ui/packages/shared/profile/src/ProfileSource.tsx, ui/packages/shared/utilities/src/time.ts
- ui: Add week and year relative time range to DatePicker
- ui: Change the timeFormat to yyyy-MM-dd HH:mm:ss
=> ui: Add week and year to presets in DateTimeRangePicker

pkg/parcacol/arrow.go, pkg/profile/writer.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/pprof.go, pkg/query/sources.go, pkg/query/table.go
Mark fields as null instead of rebuilding record during filtering.
```bash
thor@thors-MacBook-Pro ~/.../parca/pkg/query % benchstat before.txt after.txt
name           old time/op    new time/op    delta
FilterData-10    5.00ms ± 2%    0.38ms ± 1%  -92.37%  (p=0.000 n=10+10)
name           old alloc/op   new alloc/op   delta
FilterData-10    6.28MB ± 0%    0.00MB ± 1%  -99.94%  (p=0.000 n=10+10)
name           old allocs/op  new allocs/op  delta
FilterData-10     3.91k ± 1%     0.07k ± 2%  -98.19%  (p=0.000 n=10+10)
```
=> Improve filter profile data

pkg/query/flamegraph_arrow.go, pkg/query/sources.go, pkg/query/table.go
Moving to using nulls for locations instead of rebuilding means we can no longer rely on the location position to determine if it's a leaf or root. 
This changes the calculation to exclude null locations to determine leaf/root.
=> Fix root leaf calc

.github/workflows/release-dry-run.yml, .github/workflows/release.yml, scripts/free_disk_space.sh
Run script to delete unneeded dependencies to have enough disk space to cross-compile our binaries.
=> Free disk space before releasing

pkg/query/columnquery.go, pkg/query/columnquery_test.go
=> pkg/query: Don't filter unsymbolized when no function name is provided

go.mod, pkg/parca/parca.go, pkg/server/server.go
This otherwise panics on Go 1.22 now.
=> Update index to not use /* anymore for Go 1.22

ui/packages/shared/profile/src/ProfileSelector/index.tsx
This `useEffect` was causing the state reset of the selected profile on page load. 
Also, this effect seems unnecessary as it was just causing a new search effect, we could have added this as a workaround to some edge case, but the app works fine without this. So we can re-visit if any problem surfaces.
=> ui: Fixed the bug that was resetting the profile selection state on page load

pkg/debuginfo/forwarder.go, pkg/parca/parca.go
This allows the Parca server to be used as a collector within an infrastructure to point all agents or other push-based producers at a single point, to only deal with authentication for example once.
=> pkg/parca: Add forwarder mode

pkg/parcacol/querier.go, pkg/parcacol/querier_test.go, pkg/profile/profile.go, pkg/profile/reader.go, pkg/profile/writer.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/useGraphTooltip/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleGraphNodes.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/useNodeColor.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/utils.ts, ui/packages/shared/utilities/src/index.ts
For delta profiles (cpu with nanoseconds) we query the value per second, which basically is the `sum(value) / sum(duration)` per stack trace.
We already show this value in the metrics graphs. Now, the icicle graph is going to show it too. More importantly, we're going to use this for diffs.
=> Query valuePerSecond for delta profiles

ui/packages/shared/profile/src/MetricsGraph/index.tsx
This fixes a bug where when comparing profiles, and you focus on the profile on the LHS, and then use the right-click context menu to add a label to the query browser (individual label or even focusing on an entire series), the label doesn't get added to the LHS, instead the RHS.
The root cause for the bug was because we used the same ID for the right click context menu itself (even when comparing profiles), which meant there was no way to differentiate from which compare window we were actually adding the labels. I fixed by appending a random ID (generated using React's [useId](https://react.dev/reference/react/useId)) to the string `metrics-context-menu`.
=> ui: Bug fix where the metrics graph's context menu incorrectly adds labels to the query browser

.errcheck_excludes.txt, .golangci.yml, pkg/debuginfo/store_test.go, pkg/parca/parca.go, pkg/parca/parca_test.go, pkg/query/columnquery_test.go
- **pkg: Use newer grpc.NewClient over deprecated grpc.Dial**
- **Update deprecated golanglint-ci config**
=> pkg: Use new grpc.NewClient over grpc.Dial

pkg/query/columnquery.go, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ColorStackLegend.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/useMappingList.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx
Temporarily returns the labels metadata call as an empty array.
This PR also contains a fix to ensure that the icicle graph and the legend of binaries are shown together.
=> Remove the labels metadata call

pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/useGraphTooltip/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/utils.ts
It has become clear that it's not always easy for users to understand what exactly consumes resources, aka the flat value, compared to the cumulative value of a function and all of its children. 
This PR surfaces the flat value and flat value in cores/s for delta profiles in the UI for icicle graphs. 
With this change, it will be clearer that, for this example, the `scanobject` function used a total of 2.64s, including its children. The function itself, without its children, only used 700ms though (which can be seen on the right-hand side of the icicle graph where nothing is below the function itself).
=> pkg/query: Explicitly show Flat and FlatPerSecond values on icicle graph

ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx
By moving the memoized `icicleGraph` component to be above the early return statement.
=> ui: Fix the crash with the error `Rendered fewer hooks than expected`.

pkg/config/config.go, pkg/config/config_test.go, pkg/scrape/target.go, pkg/scrape/target_test.go
this updates the definition of `PprofProfilingConfig` such that a new integer field `Seconds` is added which can be set for profiles, in an attempt to resolve https://github.com/parca-dev/parca/issues/2818.
additionally, it changes the behavior where setting any profiling configurations will end up overriding the default so merge will now become a replace.
seconds is accepted as a query parameter and with this change, when provided, it will be used as scraping duration rather than the scraping interval value. this allows having scraping where process being profiled isn't under constant profiling. this only applies to configurations that have delta enabled.
https://pkg.go.dev/net/http/pprof
=> pkg/config: support seconds in pprof configuration

ui/packages/shared/parser/package.json, ui/packages/shared/parser/src/index.test.ts, ui/packages/shared/profile/src/ProfileExplorer/index.tsx, ui/packages/shared/profile/src/ProfileSource.tsx, ui/packages/shared/profile/src/__tests__/suffix_params.test.ts
This overhauls how we do selections. Since we always perform "merge" selections now this could be significantly simplified and now everything uses the parser as opposed to saving the profile name and labels separately in the URL.
=> ui: Make handling of selections more robust

pkg/debuginfo/store.go
Go build IDs are not necessarily hex.
=> pkg/debuginfo: Loosen build ID validation

snap/hooks/configure, snap/parca-wrapper
Until this commit, the default storage location for profiles on disk was in `$SNAP_DATA/profiles`, but as highlighted in both #4708 and in https://snapcraft.io/docs/data-locations, the `$SNAP_DATA` directory is versioned per-revision of the snap, whereas `$SNAP_COMMON` persists across revisions.
This change leaves config in the same location in `$SNAP_DATA`, because versioning config files with revisions might still be desirable.
Existing installs should not be affected, as the default is set on first run.
Fixes #4708
=> fix(snap): store profiles in SNAP_COMMON by default

ui/packages/shared/components/src/NoDataPrompt/index.tsx, ui/packages/shared/parser/src/selector.js, ui/packages/shared/store/src/store.ts
This ensures that we can use the Parca JS packages upstream without errors.
=> area/ui: Fix how the env var `DEV` is checked

ui/packages/shared/profile/src/SourceView/useSelectedLineRange.ts
Opening the source code viewer from the icicle graph didn’t scroll to the selected line because it only set a start line without an end line. This caused the scrolling issue. 
The problem is now fixed by setting the end line equal to the start line if the end can’t be determined.
=> area/ui: Fix the source view not scrolling to its line

ui/packages/shared/profile/src/GraphTooltipArrow/DockedGraphTooltip/index.tsx
This was added to the GraphTooltip but forgotten for the docked one.
This adds the cumulative per second and both the flat value and the flat per second value.
=> ui/packages/profile: Add flat value to DockedGraphTooltip

pkg/query/columnquery.go
It's not a given that both the `cumulativeTotal` and the `cumulativePerSecondTotal` are always bigger or smaller together. We need to check them individually. For delta profiles, we simply ignore the `diff` column anyway and only care about the `diffPerSecond` column.
=> pkg/query: Set perSecondRatios for scaling individually

pkg/query/columnquery.go
It appears that if the report type was of type `QueryRequest_REPORT_TYPE_PROFILE_METADATA` that we would still perform a merge query, throw away the samples, and then perform the metadata query.
I believe we can just perform the metadata query and not perform the merge query.
=> don't perform a merge query when report type is metadata only

ui/packages/shared/profile/src/GraphTooltipArrow/Content.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/DockedGraphTooltip/index.tsx, ui/packages/shared/profile/src/GraphTooltipArrow/useGraphTooltip/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ContextMenu.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleGraphNodes.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/useNodeColor.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/utilities/src/index.ts
The cores/s values were introduced to make profiles more comparable. With the introduction of relative comparisons, however, there is really no need for cores/s anymore.
For relative comparisons, we only show the difference as percentage, as the raw values are skewed by the scaling.
=> ui/shared/profile: Don't show cores/s values

ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileMetricsGraph/index.tsx
When profiling data is filtered with both matchers and sumBy value(s), selecting a profile in the metrics graph fails to highlight the point.
Steps to reproduce:
1. Go to demo.parca.dev/devel
2. Filter profiles (e.g., container="parca-agent")
3. Add a sumBy value (e.g., "comm")
4. Attempt to select a profile in the metrics graph
This is happening because the `findSelectedProfile` function uses label matchers from the query expression to determine 
the selected series. With sumBy, series are limited to the sumBy value, causing the function to fail as it looks for non-existent label sets.
The fix here ensures that we are correctly identifying the selected series based on the profile matchers alone or a combination of the profile matchers and the sumBy value (and prioritizing the sumBy label …
=> bug fix: Clicking on a sample should highlight it when there are query filters and sum by values

ui/packages/shared/components/src/DateTimeRangePicker/AbsoluteDatePicker/index.tsx, ui/packages/shared/components/src/DateTimeRangePicker/RelativeDatePicker/index.tsx, ui/packages/shared/components/src/DateTimeRangePicker/utils.test.ts, ui/packages/shared/components/src/DateTimeRangePicker/utils.ts, ui/packages/shared/profile/src/components/VisualisationToolbar/index.tsx
=> area/ui: Support typing multiple units in relative range picker

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/utils.ts
Using `String.fromCharCode.apply(null, buffer as unknown as number[])` is causing a "Maximum call stack size exceeded" error, especially with large amount of arrow data.
Using `TextDecoder`  instead of `String.fromCharCode` handles large arrays more efficiently.
=> area/ui: use TextDecoder to decode Arrow table into a string format

pkg/parcacol/querier.go, pkg/query/columnquery.go, ui/packages/shared/profile/src/ProfileViewWithData.tsx
Rather than querying all possible labels we want to query only for those label names that would exist within the flame graph being queried.
=> pkg/parcacol: Query flame graph metadata labels

pkg/symbol/addr2line/symtab_test.go, pkg/symbol/symbolsearcher/symbol_searcher.go
Check the size of symbol before return to avoid resovling wrong symbol.
=> Fix resovling wrong symbol when symbol table is not continous

ui/packages/shared/profile/src/components/ActionButtons/GroupByDropdown.tsx
This adds dark mode for the group by label dropdown.
=> area/ui: Add dark mode for Group by labels dropdown

ui/packages/shared/components/src/DateTimeRangePicker/utils.ts
We should be displaying all date and time in the UTC 24H format.
Replaces all usage of `lll` with `YYYY-MM-DD HH:mm:ss` as `lll` formats the date to be "Mar 20, 2024 11:30 AM" for example.
=> area/ui: Ensure all dates are in UTC

ui/packages/shared/profile/src/ProfileExplorer/ProfileExplorerCompare.tsx, ui/packages/shared/profile/src/ProfileExplorer/ProfileExplorerSingle.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx, ui/packages/shared/profile/src/SimpleMatchers/Select.tsx, ui/packages/shared/profile/src/SimpleMatchers/index.tsx
Fixes a bug where when in the simple querying mode and you add a new set of label matchers, and then proceed to move the mouse away before adding a label name, operator or value., the label matcher set is removed entirely, which can be frustrating.
Also fixes the bug where the regex input field gets so small and you don't get to see what is being typed.
=> area/ui: Fix bug of disappearing matchers

ui/packages/shared/profile/src/SimpleMatchers/Select.tsx
Fixes a bug where the height of the label value's input is too short.
Before
After
=> area/ui: fix height for selector's search

ui/packages/shared/profile/src/SimpleMatchers/Select.tsx
This fixes the following comments:
- When clicking on a value in the dropdown I expect the selected value to be set as the value in the input of the dropdown. Further on, this is going to be helpful as I only need to adjust some parts of the values for the regex from prometheus-k8s-0 to prometheus-k8s-\\d rather than still having to type the entire thing.
- Something about the Add button still seems weird. It's still floating above the input text. (24s in the video). Can we have two vertical divs? One with the input and one below with the button? Then it'll always be below and never next or above the input.
=> area/ui: Enhance regex filtering in SimpleMatchers component

pkg/query/columnquery.go
Group by address is working again with this change:
=> Don't filter out the "allowed" group by columns

ui/packages/shared/profile/src/MetricsGraph/MetricsTooltip/index.tsx, ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx
The MetricsGraph Tooltip now shows the "Per Second" in one line rather than having it split in two. All that was necessary was using a `&nbsp;`. 
Old (two lines)
New (one line)
When multiple selectors are used in the query UI, the buttons and dropdowns used to move down. This look odd and somewhat broken.
This is now fixed.
=> ui: Small improvements

pkg/symbolizer/symbolizer.go
Check the existence of debuginfo files in the temporary directory to reduce the number of copies on each request, which drives high disk usage and latency.
=> symbolizer: reduce the number of debuginfo copies

ui/packages/shared/profile/src/MatchersInput/SuggestionsList.tsx, ui/packages/shared/profile/src/MatchersInput/index.tsx, ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx, ui/packages/shared/profile/src/SimpleMatchers/index.tsx, ui/packages/shared/profile/src/contexts/MatchersInputLabelsContext.tsx, ui/packages/shared/profile/src/contexts/SimpleMatchersLabelContext.tsx, ui/packages/shared/profile/src/contexts/UtilizationLabelsContext.tsx
This pull request introduces several changes to the `ProfileSelector`, `MatchersInput`, and `SimpleMatchers` components to enhance fetching label names and values for profiling data label or utilization metrics. 
The most significant changes include the addition of a new context for utilization labels (avoiding the use of props drilling), updates to the `SimpleMatchers` and `MatchersInput` components to fetch label names and values based on whether we're in profiling data mode or utilization metrics mode.
=> area/ui: Enable displaying utilization label names and values

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/IcicleChartRootNode.tsx, ui/packages/shared/profile/src/ProfileView/components/DashboardItems/index.tsx
=> ui: Icicle chart minor UX tweaks

pkg/query/flamegraph_arrow.go
We try to append function names but the transpositions are 0 and therefore panic.
=> pkg/query: Ignore function name when empty transposition

ui/packages/shared/profile/src/MetricsGraph/MetricsContextMenu/index.tsx, ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx, ui/packages/shared/profile/src/ProfileSelector/MetricsGraphSection.tsx
This change ensures that clicking on a series in the utilization metrics graph highlights the series using a new `selectedSeries` queryParams. The previous method of using the query matchers filters away other series instead of simply just highlighting the clicked one.
Related PRs:
[area/ui: add Modify the utilization metrics graph to show multiple series](https://github.com/parca-dev/parca/pull/5538
)
[area/ui: strip attributes from context menu](https://github.com/parca-dev/parca/pull/5539)
=> area/ui: add a new queryparam `selectedSeries` to query for cpu strips and flamechart

ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
This fixes the bug of the "Create a view from this query" button not rendering upstream.
=> area/ui: Pass the `viewComponent` button to the QueryControls component

ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx
This ensures the selected timeframe in any CPU strips is reset after clicking on a new series.
=> area/ui: reset the selected_timeframe after a new series is clicked on

pkg/parcacol/querier.go, pkg/query/columnquery_test.go
Previously we would sum by all labels but this doesn't scale when there are hundreds of series available. Instead, we now have `sum by()` create a single series, much like in Prometheus. This is easier to draw and less confusing to the users.
=> pkg/parcacol: Sum into a single series if no sum by given

pkg/parcacol/querier.go, pkg/query/columnquery_test.go
Previously, we removed grouping by labels if no sum-by labels are given.
Non-delta profiles will never get sum-by labels from the UI and therefore we can hardcode grouping by labels.
=> pkg/parcacol: non-delta profiles are always grouped by label

ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/Throughput.tsx, ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx, ui/packages/shared/profile/src/MetricsGraph/utils/colorMapping.ts, ui/packages/shared/profile/src/ProfileSelector/MetricsGraphSection.tsx
This ensures that the same color is used for similar (same node, uuid and index) series in the various utilization metrics graphs.
=> area/ui: use the same color for similar nodes

ui/packages/shared/profile/src/ProfileView/components/Toolbars/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx
Add the "group by" field to the query for pprof download and pprof.me export. This makes it so the selected label set will be available in the exported data.
=> send "group by" in export requests.

ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx, ui/packages/shared/profile/src/ProfileViewWithData.tsx
This PR adds some validations on the query before querying for flamecharts and renders appropriate error message in the UI. 
Screenshots:
Valid Query:
Invalid Queries:
=> ui: Query validation for icicle chart visualization

ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx, ui/packages/shared/profile/src/MetricsGraph/utils/colorMapping.ts, ui/packages/shared/profile/src/MetricsSeries/index.tsx, ui/packages/shared/profile/src/ProfileSelector/MetricsGraphSection.tsx
Filtered out virtual labels for unique key generation in colors. Introduced a `strokeDasharray` prop to allow dashed lines, applied to limit metrics for visual distinction.
=> feat: ui: Add support for dashed lines for limit metrics in graphs

pkg/debuginfo/reader.go
Implement `objstore.ObjectSizer` interface on UploadReader to support optimized multipart uploads. This allows `objstore.TryToGetSize` to determine the total size of the upload stream, enabling proper buffer pre-allocation and improving upload performance.
The implementation tracks the running total of bytes read in the size field and returns it via `ObjectSize()`, resolving the below warning when using a S3 storage for `debuginfo`.
```
level=warn ... msg="could not guess file size for multipart upload; upload might be not optimized" name=debuginfo/8201aa879bcc815d4abc232049bb1c2a/debuginfo err="unsupported type of io.Reader: *debuginfo.UploadReader"
```
=> feat(debuginfo): implement ObjectSizer interface for UploadReader

pkg/profile/profile.go, pkg/profile/reader.go, pkg/profile/writer.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Using the collection duration for the jitter never made sense. The period describes the regular time interval between two samples, so the jitter should be based on that instead of however long the profiler decided to collect data for.
=> pkg/query: Use period for jitter not duration

pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go
Value offset allows each frame to be rendered in parallel by the frontend instead of recursively. Value offset determines the X offset, the depth of the frame the Y offset, and the cumulative the width.
This is the last piece missing that will allow the frontend to do this.
=> pkg/query: Introduce value-offset

ui/packages/shared/profile/src/ProfileExplorer/index.tsx, ui/packages/shared/utilities/src/decodeMultipleEncodings.test.ts, ui/packages/shared/utilities/src/index.ts
This PR helps to handle query expressions that have been encoded multiple times and now breaking the app. It  safely decodes strings that may have multiple levels of URL encoding with the `decodeMultipleEncodings` function.
I've also added safegaurds to ensure that we're not unnecessarily encoding query expressions multiple times by doing all the encoding for query expressions in the `filterSuffix` function.
=> ui: Properly handle multiple encodings for query expressions

ui/packages/shared/components/src/UserPreferences/index.tsx, ui/packages/shared/hooks/src/useUserPreference/index.ts, ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/TextWithEllipsis.tsx, ui/packages/shared/profile/src/ProfileView/components/Toolbars/MultiLevelDropdown.tsx
This moves the option of showing function names from lef/right side away from the user preferences settings to be an Icicle graph action.
=> ui: Change "Show function name from left side" preference to be icicle graph option

ui/packages/shared/profile/src/ProfileIcicleGraph/index.tsx
- Add user-friendly error messages for icicle chart merge conflicts
- Handle "Failed to merge flame chart records" and "Multiple samples for the same timestamp" errors
- Display clear filtering instructions to resolve overlapping data issues
=> feat: improve error handling for overlapping data in icicle charts

ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx, ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/ProfileSelector/MetricsGraphSection.tsx, ui/packages/shared/profile/src/ProfileSelector/index.tsx
The utilization metrics graph selection state was not properly handled in #5696. This PR fixes that.
=> ui: Handled the utilization metric selection state properly

ui/packages/shared/profile/src/MetricsGraph/UtilizationMetrics/index.tsx, ui/packages/shared/profile/src/MetricsGraph/index.tsx, ui/packages/shared/profile/src/MetricsSeries/index.tsx
The metrics graph needed some padding to align it to the grid scale which in turn fixed the overflows on either side.
=> ui: Fixed metrics graph alignment to the grid

ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx, ui/packages/shared/profile/src/SimpleMatchers/index.tsx
When using the "add to query" button from the metrics graph context menu, the first label would appear correctly in the SimpleMatchers component, but subsequent labels would only update the URL without reflecting in the UI until page reload.
Fixed by:
- Adding `key` prop to SimpleMatchers component to force re-render when query changes
- Improving useEffect in SimpleMatchers with proper async cleanup to prevent race conditions
=> Fix labels not appearing in SimpleMatchers after adding via context menu

ui/packages/shared/components/src/DateTimeRangePicker/RelativeDatePicker/index.tsx, ui/packages/shared/components/src/DateTimeRangePicker/utils.ts
The theory being the older `NOW`(already evaluated) instance being used in place of `to` in these `onChange` callbacks leading to a `to` that is older than the `from` which is evaluated freshly. 
We'll have to observe over time and see if this really fixes this bug scenario.
=> ui: Potential fix for the occasional time range validation error: End: start timestamp must be before end.

.github/workflows/build-test.yml
Replace QEMU-based ARM64 emulation with GitHub's native ARM64 runners now available for free in public repositories.
- Use matrix strategy for AMD64 and ARM64 builds
- Remove Docker/QEMU emulation setup
- Leverage native `ubuntu-24.04-arm` runner
=> feat: use native ARM64 runners in build-test workflow

ui/packages/shared/profile/src/ProfileSelector/MetricsGraphSection.tsx, ui/packages/shared/profile/src/ProfileView/hooks/useResetStateOnSeriesChange.ts, ui/packages/shared/profile/src/Sandwich/components/TableSection.tsx
For now, we reset the `sandwich_function_name` and `cur_path` URL state whenever a new point in the Metrics Graph series is selected. Thew newly added `ui/packages/shared/profile/src/ProfileView/hooks/useResetStateOnSeriesChange.ts` is responsible for this,
=> ui: Reset visualisation state on selection of series point

ui/packages/shared/profile/src/ProfileIcicleGraph/IcicleGraphArrow/ContextMenu.tsx, ui/packages/shared/profile/src/ProfileView/components/ViewSelector/index.tsx
Added a visible 'alpha' indicator next to the Sandwich view option in both the context menu and the view selector.
=> ui: Add 'alpha' label to Sandwich view

ui/packages/shared/profile/src/ProfileSelector/QueryControls.tsx
It's too easy to accidentally hit and each label already has its own "X".
=> ui: Remove the "X" button in the Sum by component

pkg/debuginfo/reader.go
This reverts commit b86663df0f51de0a54d726ac4acc94e34315f5d0.
#5641 uses "UploadReader.size" as "ObjectSize()", but "size" is not set when initializing, so "ObjectSize()" returns "0". Then it causes the uploaded "debuginfo" file to be size zero.
It seems currently the warning "could not guess file size for multipart upload; upload might be not optimized" has to be left.
=> Revert "feat(debuginfo): implement ObjectSizer interface for UploadReader"

.github/workflows/container.yml, .github/workflows/release-dry-run.yml, .github/workflows/snap.yml, Makefile
This small PR updates all uses of the deprecated `--skip-validate` flag in the GoReleaser CLI to the new syntax `--skip=validate`, as per [GoReleaser deprecation guidelines](https://goreleaser.com/deprecations#-skip). The changes affect both the `Makefile` and GitHub Actions workflows (`container.yml`, `release-dry-run.yml`, and `snap.yml`). This resolves warnings like the following, which are currently visible in the [CI logs](https://github.com/parca-dev/parca/actions/runs/16092547709/job/45411169934#step:9:26):
```
DEPRECATED: --skip-validate was deprecated in favor of --skip=validate, check https://goreleaser.com/deprecations#-skip for more details
````
=> Update GoReleaser commands to use new skip option

ui/packages/shared/profile/src/ProfileView/components/GroupByLabelsDropdown/index.tsx
The usage of `menuPortalTarget ` was causing a bug where the select dropdown was on top of the actual flame graph. Also added the default select dropdown styles back.
**Before**
**After**
=> Improve GroupByLabelsDropdown menu styling

pkg/scrape/scrape.go
Previously when the scrape suceeded but the function was unable to parse the result 'continue' was called which made it immediately try again since the ticker is only waited upon at the end of the loop. This can cause a huge rps spike if the endpoint is always returning invalid profiling data.
This moves the processing of the response code to a function instead that returns an error, and if an error is encountered it handles it and drops into the second select in the loop to prevent rapid reties.
=> refactor: Scrape loop.

ui/packages/shared/profile/src/ProfileFlameGraph/FlameGraphArrow/FlameGraphNodes.tsx, ui/packages/shared/profile/src/ProfileFlameGraph/FlameGraphArrow/index.tsx, ui/packages/shared/profile/src/ProfileFlameGraph/index.tsx
There was an opportunity to consolidate how the mapping files and filenames are used to derive the colors to be used for the Flame Graph. 
This PR helps to ensure we're not repeating logic in different components by using the `useProfileMetadata` and `useVisualizationState` hooks to get all the coloring data needed and passing it down as props to the components that needs them.
It also fixes a bug where if you switch the coloring by from filename to binary and vice versa, the Flame Graph is not immediately re-rendered with the new colors.
=> ui: Refactor Flame Graph color mapping logic

pkg/parcacol/querier.go
Replace `Project()` with `Distinct()` in `GetProfileMetadataMappings` and 
`GetProfileMetadataLabels` methods to ensure unique results and improve 
query performance by eliminating duplicate stacktrace and label entries.
This change will not affect correctness as GetProfileMetadataMappings
and GetProfileMetadataLabels also have deduplicate logic.
This change helps reduce 100+ million rows from the underlying database, just like #5921
=> feat: use Distinct instead of Project for profile metadata queries

ui/packages/shared/profile/src/ProfileView/components/InvertCallStack/index.tsx, ui/packages/shared/profile/src/ProfileView/hooks/useVisualizationState.ts, ui/packages/shared/test-utils/src/test-ids.ts
Also ensures flame graph state resets when group by labels are updated. (This is an actual bug detected by the E2E tests)
=> Add test IDs for Invert Call Stack button

pkg/ingester/ingester.go, pkg/ingester/ingester_test.go, pkg/normalizer/arrow.go, pkg/normalizer/normalizer.go, pkg/normalizer/otel.go, pkg/parcacol/arrow.go, pkg/parcacol/querier.go, pkg/profile/profile.go, pkg/profile/reader.go, pkg/profilestore/profilecolumnstore.go, pkg/query/columnquery.go, pkg/query/columnquery_test.go, pkg/query/flamegraph_arrow.go, pkg/query/flamegraph_arrow_test.go, pkg/query/multiple_filters_test.go, pkg/query/pprof.go, pkg/query/sources.go, pkg/query/table.go, pkg/query/table_test.go
Updated the codebase to replace all usages of `arrow.Record` with `arrow.RecordBatch` to make golang-lint happy again.
https://github.com/apache/arrow-go/pull/466 broke our golangci-lint with Arrow v18.4.1
=> Migrate from arrow.Record to arrow.RecordBatch
